import {addDoc,collection,doc,getDoc,getDocs,limit,onSnapshot,query,serverTimestamp,setDoc,Timestamp,updateDoc,where,runTransaction} from "firebase/firestore";
import {db} from "../firebase";
import {ADMIN_EMAILS,DEFAULT_PRICING,Offer,Booking,Space,emailKey} from "../pages/types";
const clean=(obj:any)=>Object.fromEntries(Object.entries(obj).filter(([,v])=>v!==undefined));
const sortNewest=(a:any,b:any)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0);
export function watchUser(uid:string,email:string,cb:(b:Booking[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"bookings"),where("userId","==",uid),limit(500)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Booking)).sort(sortNewest)),e=>onError?.(e));}
export async function backfillUserBookings(uid:string){return;}
export function watchAllBookings(cb:(b:Booking[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"bookings"),limit(500)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Booking)).sort(sortNewest)),e=>onError?.(e));}
export function watchPendingBookings(cb:(b:Booking[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"bookings"),where("status","==","Pending"),limit(500)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Booking)).sort(sortNewest)),e=>onError?.(e));}
export function watchBookingLocks(date:string,cb:(locks:any[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"bookingLocks"),where("date","==",date),limit(500)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),e=>onError?.(e));}
export function watchOffers(email:string,cb:(o:Offer[])=>void){return onSnapshot(query(collection(db,"offers"),where("active","==",true),limit(100)),s=>{const e=email.toLowerCase();cb(s.docs.map(d=>({id:d.id,...d.data()} as Offer)).filter(o=>o.targetType==="all"||(o.targetEmail||"").toLowerCase()===e));});}
export function watchRoleAssignment(email:string,cb:(a:any)=>void){return onSnapshot(doc(db,"roleAssignments",emailKey(email)),s=>cb(s.exists()?{id:s.id,...s.data()}:null));}
export function watchUsers(cb:(u:any[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"users"),limit(500)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()})).sort((a:any,b:any)=>(a.name||a.email||"").localeCompare(b.name||b.email||""))),e=>onError?.(e));}
export async function getUserByEmail(email:string):Promise<any|null>{const q=await getDocs(query(collection(db,"users"),where("email","==",emailKey(email)),limit(1)));return q.empty?null:{id:q.docs[0].id,...q.docs[0].data()};}
export async function ensureUser(u:any){const email=(u.email||"").toLowerCase(),admin=ADMIN_EMAILS.includes(email),ref=doc(db,"users",u.uid),s=await getDoc(ref),d=s.exists()?s.data():{},role=admin?"Admin":(d.role||"User");await setDoc(ref,{uid:u.uid,email,name:u.displayName||d.name||email.split("@")[0],photoURL:u.photoURL||d.photoURL||"",role,updatedAt:serverTimestamp()},{merge:true});return role;}
export async function saveUserProfile(uid:string,data:any){await updateDoc(doc(db,"users",uid),clean({...data,updatedAt:serverTimestamp()}));}
export async function loadPricing(){const s=await getDoc(doc(db,"settings","pricing"));if(!s.exists())return DEFAULT_PRICING;const raw:any=s.data();const d:any={...DEFAULT_PRICING,...raw};if(raw.conference_slot!=null&&raw.conference_hourly==null)d.conference_hourly=Number(raw.conference_slot);if(raw.desk_basic==null&&raw.cubicle_basic!=null)d.desk_basic=Number(raw.cubicle_basic);if(raw.desk_premium==null&&raw.cubicle_premium!=null)d.desk_premium=Number(raw.cubicle_premium);delete d.conference_slot;delete d.cubicle_basic;delete d.cubicle_premium;return d as typeof DEFAULT_PRICING;}
export async function savePricing(p:any){const next:any={...p};delete next.conference_slot;delete next.cubicle_basic;delete next.cubicle_premium;await setDoc(doc(db,"settings","pricing"),next,{merge:true});}
export async function loadDeskPricing(date:string,defaults:any){const s=await getDoc(doc(db,"settings","deskPricing"));const data:any=s.exists()?s.data():{};const base:any={...defaults};for(let n=1;n<=22;n++){const id=`D${String(n).padStart(2,"0")}`;base[id]=[2,3,9,15,22].includes(n)?Number(defaults[id]??DEFAULT_PRICING.desk_premium):Number(defaults[id]??DEFAULT_PRICING.desk_basic);}return {...base,...(data[date]||{})};}
export async function saveDeskPricing(date:string,prices:any){await setDoc(doc(db,"settings","deskPricing"),{[date]:prices},{merge:true});}
export async function loadWifi(){const s=await getDoc(doc(db,"settings","wifi"));return s.exists()?s.data():{ssid:"",password:"",note:""};}
export async function saveWifi(data:any){await setDoc(doc(db,"settings","wifi"),data,{merge:true});}
export async function loadUpi(){const s=await getDoc(doc(db,"settings","upi"));return s.exists()?s.data():{upiId:"",merchantName:"Coworx Central"};}
export async function saveUpi(data:any){await setDoc(doc(db,"settings","upi"),data,{merge:true});}
export async function assignManager(email:string,uid:string){const e=email.trim().toLowerCase();await setDoc(doc(db,"roleAssignments",emailKey(e)),{email:e,role:"Manager",status:"pending",assignedBy:uid,assignedAt:serverTimestamp()});const q=await getDocs(query(collection(db,"users"),where("email","==",e),limit(1)));if(!q.empty)await addDoc(collection(db,"notifications"),{recipientUid:q.docs[0].id,title:"Manager invitation",message:"An admin has invited you to become a Coworx Central Manager. Sign in and accept the invitation.",read:false,createdAt:serverTimestamp()});}
export async function acceptManager(a:any,uid:string){await updateDoc(doc(db,"roleAssignments",a.id),{status:"accepted",acceptedAt:serverTimestamp()});await updateDoc(doc(db,"users",uid),{role:"Manager"});}
export async function createOffer(data:any,uid:string){await addDoc(collection(db,"offers"),{...data,value:Number(data.value),targetEmail:data.targetType==="email"?data.targetEmail.trim().toLowerCase():"",active:true,createdBy:uid,createdAt:serverTimestamp()});}
export async function confirmBooking(id:string,uid:string,staffDiscount=0,paymentReceived?:number,paymentMethod?:string,paymentRef?:string){const ref=doc(db,"bookings",id),snap=await getDoc(ref);if(!snap.exists())throw Error("Booking not found.");const d:any=snap.data(),sd=Math.max(0,Number(staffDiscount)||0),total=Math.max(0,Number(d.base||0)-Number(d.discount||0)-sd);await updateDoc(ref,clean({status:"Confirmed",staffDiscount:sd,total,confirmedBy:uid,confirmedAt:serverTimestamp(),expiresAt:null,paymentReceived:paymentReceived===undefined?total:Number(paymentReceived),paymentMethod:paymentMethod||"Other",paymentRef:paymentRef||""}));for(const lockId of (d.lockIds||[id])){const lock=doc(db,"bookingLocks",lockId),ls=await getDoc(lock);if(ls.exists())await updateDoc(lock,{status:"Confirmed",staffDiscount:sd,total,confirmedBy:uid,confirmedAt:serverTimestamp(),expiresAt:null});}}
export async function cancelBooking(id:string,uid:string){const ref=doc(db,"bookings",id),snap=await getDoc(ref);if(!snap.exists())throw Error("Booking not found.");const d:any=snap.data();await updateDoc(ref,{status:"Cancelled",revokedBy:uid,revokedAt:serverTimestamp(),expiresAt:null});for(const lockId of (d.lockIds||[id])){const lock=doc(db,"bookingLocks",lockId),ls=await getDoc(lock);if(ls.exists())await updateDoc(lock,{status:"Cancelled",revokedBy:uid,revokedAt:serverTimestamp(),expiresAt:null});}}
export const revokeBooking=cancelBooking;
export async function markCheckIn(id:string){await updateDoc(doc(db,"bookings",id),{checkedInAt:serverTimestamp()});}
export async function markCheckOut(id:string){await updateDoc(doc(db,"bookings",id),{checkedOutAt:serverTimestamp()});}
export async function createBooking(input:{date:string;endDate?:string;days?:number;dates?:string[];space:Space;inventoryId:string;inventoryIds?:string[];lockKeys?:string[];label:string;userId:string;userEmail:string;customerName?:string;customerEmail?:string;customerPhone?:string;createdByRole?:string;walkIn?:boolean;start?:string;end?:string;durationHours?:number;base:number;discount:number;total:number;offerId?:string|null;status?:"Pending"|"Confirmed"}){const dates=input.dates?.length?input.dates:[input.date],ids=input.inventoryIds?.length?input.inventoryIds:[input.inventoryId],timed=!!input.start,hoursPerDay=timed?Math.max(1,Math.round((input.durationHours||1)/Math.max(1,dates.length))):1,generatedLockKeys:string[]=[],lockInventories:string[]=[];if(timed){for(const day of dates){for(let i=0;i<hoursPerDay;i++){const [hh,mm]=(input.start||"09:00").split(":").map(Number),n=hh*60+mm+i*60,slot=`${String(Math.floor(n/60)%24).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;generatedLockKeys.push(`${day}_${input.space}_${slot}`);lockInventories.push(ids[0]);}}}else{for(const day of dates)for(const id of ids){generatedLockKeys.push(`${day}_${id}_day`);lockInventories.push(id);}}const finalLockKeys=input.lockKeys?.length?input.lockKeys:generatedLockKeys,bookingRef=doc(collection(db,"bookings")),expiresAt=Timestamp.fromMillis(Date.now()+15*60*1000),finalStatus=input.status||"Pending";if(lockInventories.length!==finalLockKeys.length)throw Error("Booking configuration is invalid.");await runTransaction(db,async tx=>{const lockRefs=finalLockKeys.map(k=>doc(db,"bookingLocks",k.replace(/[^a-zA-Z0-9_-]/g,"-"))),locks=await Promise.all(lockRefs.map(r=>tx.get(r)));for(const lock of locks){if(lock.exists()){const ld:any=lock.data(),active=ld.status==="Confirmed"||(ld.status==="Pending"&&(ld.expiresAt?.toMillis?.()||0)>Date.now());if(active)throw Error("One or more selected desks or time slots are already booked.");}}const payload=clean({...input,dates,endDate:input.endDate||dates[dates.length-1],days:input.days||dates.length,inventoryIds:ids,lockIds:lockRefs.map(r=>r.id),status:finalStatus,expiresAt:finalStatus==="Confirmed"?null:expiresAt,createdAt:serverTimestamp()});tx.set(bookingRef,payload);for(let i=0;i<lockRefs.length;i++){const k=finalLockKeys[i],parts=k.split("_"),day=parts.shift()||input.date,rest=parts.join("_"),slot=timed?rest:null;tx.set(lockRefs[i],clean({bookingId:bookingRef.id,inventoryId:lockInventories[i],date:day,start:slot,end:timed?input.end||null:null,userId:input.userId,status:finalStatus,expiresAt:finalStatus==="Confirmed"?null:expiresAt,updatedAt:serverTimestamp()}));}});return{id:bookingRef.id,expiresAt};}
