import {addDoc,collection,doc,getDoc,getDocs,limit,onSnapshot,query,serverTimestamp,setDoc,Timestamp,updateDoc,where,runTransaction} from "firebase/firestore";
import {db} from "../firebase";
import {ADMIN_EMAILS,DEFAULT_PRICING,Offer,Booking,Space,emailKey} from "../pages/types";
const clean=(obj:any)=>Object.fromEntries(Object.entries(obj).filter(([,v])=>v!==undefined));
const sortNewest=(a:any,b:any)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0);
export function watchUser(uid:string,email:string,cb:(b:Booking[])=>void,onError?:(e:any)=>void){let mirrored:Booking[]=[];let legacy:Booking[]=[];const emit=()=>{const m=new Map<string,Booking>();[...mirrored,...legacy].forEach(b=>m.set(b.id,b));cb([...m.values()].sort(sortNewest));};const a=onSnapshot(query(collection(db,"userBookings",uid,"bookings"),limit(300)),s=>{mirrored=s.docs.map(d=>({id:d.id,...d.data()} as Booking));emit()},e=>onError?.(e));const b=onSnapshot(query(collection(db,"bookings"),where("userId","==",uid),limit(300)),s=>{legacy=s.docs.map(d=>({id:d.id,...d.data()} as Booking));emit()},e=>onError?.(e));return()=>{a();b()};}
export async function backfillUserBookings(uid:string){const snap=await getDocs(query(collection(db,"bookings"),where("userId","==",uid),limit(300)));if(snap.empty)return;const writes=snap.docs.map(d=>setDoc(doc(db,"userBookings",uid,"bookings",d.id),{id:d.id,...d.data()},{merge:true}));await Promise.all(writes);}
export function watchAllBookings(cb:(b:Booking[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"bookings"),limit(300)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Booking)).sort(sortNewest)),e=>onError?.(e));}
export function watchPendingBookings(cb:(b:Booking[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"bookings"),where("status","==","Pending"),limit(300)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Booking)).sort(sortNewest)),e=>onError?.(e));}
export function watchBookingLocks(date:string,cb:(locks:any[])=>void,onError?:(e:any)=>void){return onSnapshot(query(collection(db,"bookingLocks"),where("date","==",date),limit(300)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))),e=>onError?.(e));}
export function watchOffers(email:string,cb:(o:Offer[])=>void){return onSnapshot(query(collection(db,"offers"),where("active","==",true),limit(100)),s=>{const e=email.toLowerCase();cb(s.docs.map(d=>({id:d.id,...d.data()} as Offer)).filter(o=>o.targetType==="all"||(o.targetEmail||"").toLowerCase()===e));});}
export function watchRoleAssignment(email:string,cb:(a:any)=>void){return onSnapshot(doc(db,"roleAssignments",emailKey(email)),s=>cb(s.exists()?{id:s.id,...s.data()}:null));}
export async function ensureUser(u:any){const email=(u.email||"").toLowerCase();const admin=ADMIN_EMAILS.includes(email),ref=doc(db,"users",u.uid),s=await getDoc(ref),d=s.exists()?s.data():{},role=admin?"Admin":(d.role||"User");await setDoc(ref,{uid:u.uid,email,name:u.displayName||d.name||"Coworx Member",photoURL:u.photoURL||d.photoURL||"",role,updatedAt:serverTimestamp()},{merge:true});return role;}
export async function loadPricing(){const s=await getDoc(doc(db,"settings","pricing"));return s.exists()?{...DEFAULT_PRICING,...s.data()} as typeof DEFAULT_PRICING:DEFAULT_PRICING;}
export async function savePricing(p:any){await setDoc(doc(db,"settings","pricing"),p,{merge:true});}
export async function assignManager(email:string,uid:string){const e=email.trim().toLowerCase();await setDoc(doc(db,"roleAssignments",emailKey(e)),{email:e,role:"Manager",status:"pending",assignedBy:uid,assignedAt:serverTimestamp()});const q=await getDocs(query(collection(db,"users"),where("email","==",e),limit(1)));if(!q.empty)await addDoc(collection(db,"notifications"),{recipientUid:q.docs[0].id,title:"Manager invitation",message:"An admin has invited you to become a Coworx Central Manager. Sign in and accept the invitation.",read:false,createdAt:serverTimestamp()});}
export async function acceptManager(a:any,uid:string){await updateDoc(doc(db,"roleAssignments",a.id),{status:"accepted",acceptedAt:serverTimestamp()});await updateDoc(doc(db,"users",uid),{role:"Manager"});}
export async function createOffer(data:any,uid:string){await addDoc(collection(db,"offers"),{...data,value:Number(data.value),targetEmail:data.targetType==="email"?data.targetEmail.trim().toLowerCase():"",active:true,createdBy:uid,createdAt:serverTimestamp()});}
export async function confirmBooking(id:string,uid:string,staffDiscount=0,paymentReceived?:number,paymentMethod?:string,paymentRef?:string){const ref=doc(db,"bookings",id);const snap=await getDoc(ref);if(!snap.exists())throw Error("Booking not found.");const d:any=snap.data();const sd=Math.max(0,Number(staffDiscount)||0),total=Math.max(0,Number(d.base||0)-Number(d.discount||0)-sd);await updateDoc(ref,clean({status:"Confirmed",staffDiscount:sd,total,confirmedBy:uid,confirmedAt:serverTimestamp(),expiresAt:null,paymentReceived:paymentReceived===undefined?total:Number(paymentReceived),paymentMethod:paymentMethod||"Other",paymentRef:paymentRef||""}));const lock=doc(db,"bookingLocks",id);const ls=await getDoc(lock);if(ls.exists())await updateDoc(lock,{status:"Confirmed",staffDiscount:sd,total,confirmedBy:uid,confirmedAt:serverTimestamp(),expiresAt:null});const userId=d.userId as string;if(userId&&!userId.startsWith("walkin:")){try{await updateDoc(doc(db,"userBookings",userId,"bookings",id),clean({status:"Confirmed",staffDiscount:sd,total,confirmedBy:uid,confirmedAt:serverTimestamp(),expiresAt:null,paymentReceived:paymentReceived===undefined?total:Number(paymentReceived),paymentMethod:paymentMethod||"Other",paymentRef:paymentRef||""}))}catch{}}
}
export async function revokeBooking(id:string,uid:string){const ref=doc(db,"bookings",id);const snap=await getDoc(ref);if(!snap.exists())throw Error("Booking not found.");const b:any=snap.data();if(b.status!=="Pending")throw Error("Only pending requests can be revoked.");await updateDoc(ref,{status:"Cancelled",revokedBy:uid,revokedAt:serverTimestamp(),expiresAt:null});const lock=doc(db,"bookingLocks",id);const ls=await getDoc(lock);if(ls.exists())await updateDoc(lock,{status:"Cancelled",revokedBy:uid,revokedAt:serverTimestamp(),expiresAt:null});if(b.userId&&!String(b.userId).startsWith("walkin:"))try{await updateDoc(doc(db,"userBookings",b.userId,"bookings",id),{status:"Cancelled",revokedBy:uid,revokedAt:serverTimestamp(),expiresAt:null})}catch{} }
export async function createBooking(input:{date:string;space:Space;inventoryId:string;label:string;userId:string;userEmail:string;customerEmail?:string;customerPhone?:string;createdByRole?:string;walkIn?:boolean;start?:string;end?:string;base:number;discount:number;total:number;offerId?:string|null;status?:"Pending"|"Confirmed"}){const startKey=input.start||"day";const key=`${input.date}_${input.inventoryId}_${startKey}`.replace(/[^a-zA-Z0-9_-]/g,"-");const bookingRef=doc(db,"bookings",key);const lockRef=doc(db,"bookingLocks",key);const expiresAt=Timestamp.fromMillis(Date.now()+15*60*1000);const finalStatus=input.status||"Pending";await runTransaction(db,async tx=>{const lock=await tx.get(lockRef);if(lock.exists()){const ld:any=lock.data();const active=ld.status==="Confirmed"||(ld.status==="Pending"&&(ld.expiresAt?.toMillis?.()||0)>Date.now());if(active)throw Error("That seat or time slot is already booked.");}const payload=clean({...input,status:finalStatus,expiresAt:finalStatus==="Confirmed"?null:expiresAt,createdAt:serverTimestamp()});const lockPayload=clean({bookingId:key,inventoryId:input.inventoryId,date:input.date,start:input.start||null,end:input.end||null,userId:input.userId,customerEmail:input.customerEmail||null,customerPhone:input.customerPhone||null,status:finalStatus,expiresAt:finalStatus==="Confirmed"?null:expiresAt,updatedAt:serverTimestamp()});tx.set(lockRef,lockPayload);tx.set(bookingRef,payload);if(!input.userId.startsWith("walkin:"))tx.set(doc(db,"userBookings",input.userId,"bookings",key),payload);});return{id:key,expiresAt};}
