import {addDoc,collection,doc,getDoc,getDocs,limit,onSnapshot,query,serverTimestamp,setDoc,Timestamp,updateDoc,where,runTransaction} from "firebase/firestore";
import {db} from "../firebase";
import {ADMIN_EMAIL,DEFAULT_PRICING,Offer,Booking,Space,emailKey} from "../pages/types";
export function watchUser(uid:string,cb:(b:Booking[])=>void){return onSnapshot(query(collection(db,"bookings"),where("userId","==",uid)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Booking))));}
export function watchAllBookings(cb:(b:Booking[])=>void){return onSnapshot(query(collection(db,"bookings"),limit(300)),s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Booking))));}
export function watchOffers(email:string,cb:(o:Offer[])=>void){return onSnapshot(query(collection(db,"offers"),where("active","==",true),limit(100)),s=>{const e=email.toLowerCase();cb(s.docs.map(d=>({id:d.id,...d.data()} as Offer)).filter(o=>o.targetType==="all"||(o.targetEmail||"").toLowerCase()===e));});}
export function watchRoleAssignment(email:string,cb:(a:any)=>void){return onSnapshot(doc(db,"roleAssignments",emailKey(email)),s=>cb(s.exists()?{id:s.id,...s.data()}:null));}
export async function ensureUser(u:any){const admin=(u.email||"").toLowerCase()===ADMIN_EMAIL,ref=doc(db,"users",u.uid),s=await getDoc(ref),d=s.exists()?s.data():{},role=admin?"Admin":(d.role||"User");await setDoc(ref,{uid:u.uid,email:(u.email||"").toLowerCase(),name:u.displayName||d.name||"Coworx Member",photoURL:u.photoURL||d.photoURL||"",role,updatedAt:serverTimestamp()},{merge:true});return role;}
export async function loadPricing(){const s=await getDoc(doc(db,"settings","pricing"));return s.exists()?{...DEFAULT_PRICING,...s.data()} as typeof DEFAULT_PRICING:DEFAULT_PRICING;}
export async function savePricing(p:any){await setDoc(doc(db,"settings","pricing"),p,{merge:true});}
export async function assignManager(email:string,uid:string){const e=email.trim().toLowerCase();await setDoc(doc(db,"roleAssignments",emailKey(e)),{email:e,role:"Manager",status:"pending",assignedBy:uid,assignedAt:serverTimestamp()});const q=await getDocs(query(collection(db,"users"),where("email","==",e),limit(1)));if(!q.empty)await addDoc(collection(db,"notifications"),{recipientUid:q.docs[0].id,title:"Manager invitation",message:"An admin has invited you to become a Coworx Central Manager. Sign in and accept the invitation.",read:false,createdAt:serverTimestamp()});}
export async function acceptManager(a:any,uid:string){await updateDoc(doc(db,"roleAssignments",a.id),{status:"accepted",acceptedAt:serverTimestamp()});await updateDoc(doc(db,"users",uid),{role:"Manager"});}
export async function createOffer(data:any,uid:string){await addDoc(collection(db,"offers"),{...data,value:Number(data.value),targetEmail:data.targetType==="email"?data.targetEmail.trim().toLowerCase():"",active:true,createdBy:uid,createdAt:serverTimestamp()});}
export async function confirmBooking(id:string,uid:string){await updateDoc(doc(db,"bookings",id),{status:"Confirmed",confirmedBy:uid,confirmedAt:serverTimestamp()});}
export async function createBooking(input:{date:string;space:Space;inventoryId:string;label:string;userId:string;userEmail:string;start?:string;end?:string;base:number;discount:number;total:number;offerId?:string|null}){const key=`${input.date}_${input.inventoryId}_${input.start||"day"}`.replace(/[^a-zA-Z0-9_-]/g,"-"),ref=doc(db,"bookings",key),expiresAt=Timestamp.fromMillis(Date.now()+15*60*1000);await runTransaction(db,async tx=>{const existing=await tx.get(ref);if(existing.exists()){const d:any=existing.data(),active=d.status==="Confirmed"||(d.status==="Pending"&&(d.expiresAt?.toMillis?.()||0)>Date.now());if(active)throw Error("That seat or time slot is already booked.");}tx.set(ref,{...input,status:"Pending",expiresAt,createdAt:serverTimestamp()});});return {id:key,expiresAt};}
