import React,{useMemo,useState} from "react";
import {CalendarDays,Clock3,Lock,MessageCircle,Timer,UserPlus,Phone,Monitor,KeyRound,Building2,Mic2,Users,CheckCircle2,AlertCircle,Percent} from "lucide-react";
import {Space,desks,confStarts,meetingStarts,podStarts,addHours,dateSpan,BUSINESS_START,BUSINESS_END} from "./types";
import {createBooking,getUserByEmail,saveUserProfile} from "../lib/firestore";
import conferenceImage from "../assets/conference-2.webp";import podcastImage from "../assets/podcast.webp";
import "./booking.css";import "./ui-fixes.css";import "./multi-day.css";
const activeLock=(l:any)=>l.status==="Confirmed"||(l.status==="Pending"&&(l.expiresAt?.toMillis?.()||0)>Date.now());
const isBusy=(locks:any[],space:Space,slot:string)=>locks.some(l=>l.inventoryId===space&&activeLock(l)&&l.start===slot);
const maxFreeHours=(locks:any[],space:Space,start:string)=>{let n=0;for(let i=0;i<10;i++){const slot=addHours(start,i);if(slot>=BUSINESS_END||isBusy(locks,space,slot))break;n++;}return n;};
const roomBookedTimes=(locks:any[],space:Space)=>Array.from(new Set(locks.filter(l=>l.inventoryId===space&&activeLock(l)&&l.start).map(l=>`${l.start}–${l.end||addHours(l.start,1)}`))).sort();
const deskLayout:Array<string|null>=["D04","D03","D02","D01","D05","D06","D07","D08","D11","D10","D09",null,"D12","D13","D14","D15","D19","D18","D17","D16","D20","D21","D22",null];
const deskById=Object.fromEntries(desks.map(d=>[d.id,d]));
export default function Booking(p:any){
 const selectedSeats=p.selectedSeats||[],roomLocks=p.roomLocks||[];
 const [endDate,setEndDate]=useState(p.date),[profileOpen,setProfileOpen]=useState(false),[bookingResult,setBookingResult]=useState("");
 const [profile,setProfile]=useState({mobile:p.phoneNumber||"",gender:"",dob:"",profession:""});
 const start=p.space==="conference"?p.conf:p.space==="meeting"?p.meeting:p.pod;
 const roomMax=maxFreeHours(roomLocks,p.space,start),duration=p.space==="conference"?p.confDuration:p.space==="meeting"?p.meetingDuration:p.podDuration;
 const end=addHours(start,duration),isTimed=p.space!=="desk"&&p.space!=="cubicle",isValidHours=!isTimed||(start>=BUSINESS_START&&end<=BUSINESS_END&&start<end);
 const bookedTimes=isTimed?roomBookedTimes(roomLocks,p.space):[];const dates=useMemo(()=>dateSpan(p.date,endDate),[p.date,endDate]);const days=dates.length;
 const spaceTitle=p.space==="desk"||p.space==="cubicle"?"Desk":p.space==="meeting"?"Meeting Room":p.space==="conference"?"Conference Room":"Creator Studio";
 const roomStartOptions:string[]=p.space==="meeting"?meetingStarts:p.space==="conference"?confStarts:podStarts;
 const dailyBase=!isTimed?selectedSeats.reduce((sum:number,id:string)=>{const s=deskById[id];return sum+Number(p.deskPrices?.[id]??(s?.premium?p.prices.desk_premium:p.prices.desk_basic))},0):((p.space==="conference"?p.prices.conference_hourly:p.space==="meeting"?p.prices.meeting_hourly:p.prices.podcast_hourly)*duration);
 const subtotal=dailyBase*Math.max(0,days),offer=p.offers?.[0];
 const offerDiscount=offer?(offer.type==="percent"?Math.round(subtotal*Number(offer.value||0)/100):Math.min(subtotal,Number(offer.value)||0)):0;
 const bulkDiscount=!isTimed&&selectedSeats.length>5?Math.round(subtotal*.1):0,stayDiscount=days>=5?Math.round(subtotal*.1):0;
 const discount=Math.min(subtotal,offerDiscount+bulkDiscount+stayDiscount),total=Math.max(0,subtotal-discount);
 const setRoomStart=(v:string)=>{const max=maxFreeHours(roomLocks,p.space,v);if(p.space==="meeting"){p.setMeeting(v);if(p.meetingDuration>max)p.setMeetingDuration(Math.max(1,max||1));}else if(p.space==="conference"){p.setConf(v);if(p.confDuration>max)p.setConfDuration(Math.max(1,max||1));}else{p.setPod(v);if(p.podDuration>max)p.setPodDuration(Math.max(1,max||1));}};
 const setRoomDuration=(n:number)=>p.space==="meeting"?p.setMeetingDuration(n):p.space==="conference"?p.setConfDuration(n):p.setPodDuration(n);
 const toggleSeat=(id:string)=>{if(p.booked.includes(`seat-${id}`)||p.booked.includes(`desk-${id}`))return;p.setSelectedSeats(selectedSeats.includes(id)?selectedSeats.filter((x:string)=>x!==id):[...selectedSeats,id])};
 const submit=()=>{if(!dates.length||!isValidHours||(isTimed&&(!roomMax||duration>roomMax)))return;setBookingResult("");setProfile({mobile:p.phoneNumber||profile.mobile,gender:profile.gender,dob:profile.dob,profession:profile.profession});setProfileOpen(true)};
 const completeBooking=async()=>{const phone=profile.mobile.trim(),targetEmail=p.staffBooking?(p.customerEmail||"").trim().toLowerCase():p.user?.email||"";if(!targetEmail.includes("@")){setBookingResult("Enter a valid customer email address.");return}if(!/^\+?[0-9\s()-]{10,18}$/.test(phone)){setBookingResult("Enter a valid mobile number.");return}if(!dates.length){setBookingResult("Choose a valid date range.");return}if(isTimed&&(!roomMax||duration>roomMax)){setBookingResult("That time and duration are no longer available. Please choose another slot.");return}try{let customerName=p.user?.displayName||p.user?.email?.split("@")[0]||"Coworx Member";if(p.staffBooking){const existing=await getUserByEmail(targetEmail);if(existing?.name)customerName=existing.name}else{try{await saveUserProfile(p.user.uid,{phone,gender:profile.gender,dob:profile.dob,profession:profile.profession})}catch{}}
 const ids=isTimed?[p.space]:selectedSeats.map((s:string)=>`desk-${s}`),label=isTimed?spaceTitle:`${selectedSeats.length} Desk${selectedSeats.length===1?"":"s"}`;
 await createBooking({date:p.date,endDate,days,dates,space:p.space,inventoryId:ids[0],inventoryIds:ids,label,userId:p.staffBooking?`walkin:${targetEmail}`:p.user.uid,userEmail:p.user?.email||"",customerName,customerEmail:targetEmail,customerPhone:phone,createdByRole:p.staffBooking?(p.staff?"Staff":"User"):"User",walkIn:!!p.staffBooking,start:isTimed?start:undefined,end:isTimed?end:undefined,durationHours:isTimed?duration*days:days,base:subtotal,discount,total,offerId:offer?.id||null,status:p.staffBooking?"Confirmed":"Pending"});
 if(!p.staffBooking){const promo=days>=5?` 5+ day stay discount 10% applied. Total: ₹${total}.`:` Total: ₹${total}.`;window.open(`https://wa.me/919970836509?text=${encodeURIComponent(`Hello Coworx Central, I want to book ${label} from ${p.date} to ${endDate}${isTimed?` (${start}-${end} each day)`:" (full business day)"}.${promo} Contact: ${phone}.`)}`,"_blank")}
 setBookingResult(p.staffBooking?`Booking confirmed for ${targetEmail}. ${days} day${days===1?"":"s"}.`:`Request created. ${days} day${days===1?"":"s"} held for 15 minutes.`);setProfileOpen(false);p.setSelectedSeats([]);p.setStaffBooking(false);p.setCustomerEmail("")}catch(e:any){setBookingResult(e?.message||"Booking failed. One or more dates may already be booked.")}};
 return <main className="page bookingPage"><div className="bookingIntro"><div><span className="eyebrow">MAKE A RESERVATION</span><h2>{p.staffBooking?"Book for a customer":"Choose your workspace."}</h2><p>Working hours are <strong>9:00 AM–7:00 PM</strong> for desks, meeting room, conference room and creator studio. Every timed booking must finish by 7:00 PM.</p></div>{p.staff&&<div className="staffMode"><span>Staff booking</span><div className="staffToggle"><button className={!p.staffBooking?"active":""} onClick={()=>p.setStaffBooking(false)}>My booking</button><button className={p.staffBooking?"active":""} onClick={()=>p.setStaffBooking(true)}><UserPlus size={15}/> Walk-in customer</button></div></div>}{p.staffBooking&&<div className="customerBox"><div className="customerFields"><label>Customer email address<input required type="email" placeholder="customer@gmail.com" value={p.customerEmail} onChange={(e:any)=>p.setCustomerEmail(e.target.value)}/></label><label><span>Customer mobile number <b>*</b></span><div className="phoneInput"><Phone size={16}/><input required type="tel" placeholder="+91 98765 43210" value={p.phoneNumber} onChange={(e:any)=>p.setPhoneNumber(e.target.value)}/></div></label></div><small>We use the email to identify the customer and the phone to contact them.</small></div>}{!p.staffBooking&&<div className="customerBox userContact"><label><span>Your mobile number <b>*</b></span><div className="phoneInput"><Phone size={16}/><input required type="tel" placeholder="+91 98765 43210" value={p.phoneNumber} onChange={(e:any)=>p.setPhoneNumber(e.target.value)}/></div></label><small>Your Google name is fetched automatically. Extra profile details are collected only when you submit the booking.</small></div>}</div>
 <div className="bookingGrid"><section className="panel bookingPanel"><div className="dateRangeBox"><label><span>START DATE</span><input type="date" min={new Date().toISOString().slice(0,10)} value={p.date} onChange={(e:any)=>{p.setDate(e.target.value);if(endDate<e.target.value)setEndDate(e.target.value)}}/></label><div className="rangeArrow">→</div><label><span>END DATE</span><input type="date" min={p.date} value={endDate} onChange={(e:any)=>setEndDate(e.target.value)}/></label><div className="rangeSummary"><CalendarDays size={17}/><strong>{days||0} day{days===1?"":"s"}</strong><small>{days>=5?"10% multi-day discount unlocked":"Book 5+ days and save 10%"}</small></div></div>
 <div className="tabs">{([["desk","Desks"],["meeting","Meeting Room"],["conference","Conference Room"],["podcast","Creator Studio"]] as [Space,string][]).map(([s,l])=><button key={s} className={p.space===s||s==="desk"&&p.space==="cubicle"?"active":""} onClick={()=>{p.setSpace(s);p.setSelectedSeats([])}}>{l}</button>)}</div>
 {(p.space==="desk"||p.space==="cubicle")&&<><div className="workingHoursBanner"><Clock3/> <b>Open 9:00 AM–7:00 PM</b><span>Desk booking = full business day</span></div><div className="panelHead"><div><h3>22 desk floor map</h3><small>Matches the physical arrangement. Premium desks have the lockable drawer.</small></div><b>₹{p.prices.desk_basic} regular · ₹{p.prices.desk_premium} premium</b></div><div className="deskBulkNote">{selectedSeats.length?`${selectedSeats.length} desk${selectedSeats.length===1?"":"s"} selected`:"Select desks from the floor plan"}{selectedSeats.length>5&&<span>10% bulk discount applied</span>}</div><div className="seatGrid redesignedDeskGrid floorPlanGrid">{deskLayout.map((id,idx)=>{if(!id)return <div key={`pillar-${idx}`} className="pillarGap" aria-label="Structural pillar space"><span>PILLAR</span></div>;const s=deskById[id];const b=p.booked.includes(`desk-${id}`)||p.booked.includes(`seat-${id}`),sel=selectedSeats.includes(id),price=p.deskPrices?.[id]??(s.premium?p.prices.desk_premium:p.prices.desk_basic);return <button key={id} disabled={b} className={`seat deskCard ${b?"booked":""} ${sel?"selected":""}`} onClick={()=>toggleSeat(id)}><span className="deskIcons"><Monitor size={30}/>{s.premium&&<KeyRound className="premiumKeyIcon" size={22} aria-label="Premium desk with lockable drawer"/>}</span><strong>{s.number}</strong><b>₹{price}/day</b><small>{b?"BOOKED":s.premium?"PREMIUM · DRAWER + LOCK":"REGULAR DESK"}</small>{sel&&<span className="deskCheck"><CheckCircle2/></span>}</button>})}</div><div className="floorLegend"><span><i className="legendDesk"/> Desk</span><span><i className="legendPremiumIcon"><KeyRound size={12}/></i> Premium / drawer + lock</span><span><i className="legendPillar"/> Pillar / blank space</span></div></>}
 {isTimed&&<TimeRoom image={p.space==="conference"?conferenceImage:p.space==="podcast"?podcastImage:null} icon={p.space==="meeting"?<Users/>:p.space==="conference"?<Building2/>:<Mic2/>} title={spaceTitle} capacity={p.space==="meeting"?"8 seats":p.space==="conference"?"18 seats":"Creator room"} price={p.space==="conference"?p.prices.conference_hourly:p.space==="meeting"?p.prices.meeting_hourly:p.prices.podcast_hourly} starts={roomStartOptions} value={start} setStart={setRoomStart} duration={duration} setDuration={setRoomDuration} maxHours={roomMax} bookedTimes={bookedTimes} note={p.space==="meeting"?"8-seater · ₹600/hour · book multiple hours · AC · Wi-Fi · power":p.space==="conference"?"18-seater · ₹500/hour · book multiple hours · U-shaped table · AC · Wi-Fi · power modules":"Hourly · lights · microphones · stands · everything included · camera not provided"} working="9:00 AM–7:00 PM"/>}
 </section><aside className="summary panel"><span className="eyebrow">BOOKING SUMMARY</span><h3>{selectedSeats.length?`${selectedSeats.length} Desk${selectedSeats.length===1?"":"s"} Selected`:spaceTitle}</h3><p><CalendarDays/> {p.date}{endDate!==p.date&&<> → {endDate}</>}</p>{isTimed&&<p><Clock3/> {start}–{end} · {duration} hr{duration===1?"":"s"} / day</p>}{!isTimed&&selectedSeats.length>0&&<p><Monitor/> {selectedSeats.join(", ")}</p>}<p><Clock3/> Business hours: 9:00 AM–7:00 PM</p>{isTimed&&bookedTimes.length>0&&<div className="bookedTimesBox"><strong>Already booked on start date</strong><div>{bookedTimes.map(t=><span key={t}>{t}</span>)}</div></div>}<hr/><div className="money"><span>Daily price</span><b>₹{dailyBase}</b></div><div className="money"><span>{days} day{days===1?"":"s"}</span><b>₹{subtotal}</b></div>{stayDiscount>0&&<div className="money good"><span><Percent size={13}/> 5+ day stay discount (10%)</span><b>−₹{stayDiscount}</b></div>}{bulkDiscount>0&&<div className="money good"><span>6+ desk discount (10%)</span><b>−₹{bulkDiscount}</b></div>}{offerDiscount>0&&<div className="money good"><span>Offer discount</span><b>−₹{offerDiscount}</b></div>}<div className="money total"><span>Total to request</span><strong>₹{total}</strong></div>{days>=5&&<div className="multiDayPromo"><Percent/><div><strong>10% multi-day discount applied</strong><small>Valid for 5 or more consecutive days.</small></div></div>}{offer&&<div className="offerMini"><b>{offer.title}</b><small>{offer.type==="percent"?`${offer.value}% OFF`:`₹${offer.value} OFF`}</small></div>}<div className="lock"><Lock/> {p.staffBooking?"Staff booking confirms immediately.":"Your selection is held for 15 minutes after request submission."}</div>{bookingResult&&<div className="bookingSuccess"><CheckCircle2/><span>{bookingResult}</span></div>}<button className="whatsapp" onClick={submit} disabled={(!selectedSeats.length&&!isTimed)||!dates.length||!isValidHours||(isTimed&&(!roomMax||duration>roomMax))}>{p.staffBooking?"Confirm customer booking":"Request on WhatsApp"}<MessageCircle/></button>{isTimed&&roomMax<1&&<small className="error"><AlertCircle/> No free time remains from {start}. Choose another start time.</small>}{isTimed&&roomMax>0&&duration>roomMax&&<small className="error">Only {roomMax} hour{roomMax===1?"":"s"} are available from {start}. Booking must finish by 7:00 PM and cannot overlap an existing booking.</small>}</aside></div>
 {profileOpen&&<ProfileModal profile={profile} setProfile={setProfile} name={p.user?.displayName||p.user?.email?.split("@")[0]||"Coworx Member"} onClose={()=>setProfileOpen(false)} onContinue={completeBooking} error={bookingResult}/>}</main>;
}
function ProfileModal({profile,setProfile,name,onClose,onContinue,error}:any){return <div className="modalBackdrop"><div className="modalCard"><div className="modalHead"><div><span className="eyebrow">CUSTOMER DETAILS</span><h3>Complete your booking</h3></div><button onClick={onClose}>×</button></div><div className="identityBox"><strong>{name}</strong><span>Name fetched from your Google account</span></div><div className="formGrid compact"><label>Mobile number <b>*</b><input required type="tel" value={profile.mobile} onChange={(e:any)=>setProfile({...profile,mobile:e.target.value})}/></label><label>Gender<select value={profile.gender} onChange={(e:any)=>setProfile({...profile,gender:e.target.value})}><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option><option>Prefer not to say</option></select></label><label>Date of birth<input type="date" value={profile.dob} onChange={(e:any)=>setProfile({...profile,dob:e.target.value})}/></label><label>Profession<input placeholder="Designer, student, founder…" value={profile.profession} onChange={(e:any)=>setProfile({...profile,profession:e.target.value})}/></label></div>{error&&<small className="error">{error}</small>}<small className="muted">Your profile details are stored with your Coworx account and are not added to the WhatsApp message.</small><div className="modalFooter"><button className="ghost" onClick={onClose}>Back</button><button className="primary" onClick={onContinue}>Continue <MessageCircle/></button></div></div></div>}
function TimeRoom({image,icon,title,capacity,price,starts,value,setStart,duration,setDuration,maxHours,bookedTimes,note,working}:any){return <div className="room"><div className="roomVisual">{image?<img src={image} alt={title}/>:<div className="roomIconHero">{icon}</div>}</div><div className="workingHoursBanner"><Clock3/> <b>Open {working}</b><span>{capacity}</span></div><div className="panelHead"><div><h3>{title}</h3><small>{note}</small></div><b>₹{price} / hour</b></div>{bookedTimes?.length>0?<div className="roomAvailability"><div><strong>Already booked today</strong><small>These times are blocked.</small></div><div>{bookedTimes.map((t:string)=><span key={t}>{t}</span>)}</div></div>:<div className="roomAvailability empty"><strong>No bookings yet for this date</strong><small>All time slots are currently open.</small></div>}<label>Start time<select value={value} onChange={(e:any)=>setStart(e.target.value)}>{starts.map((x:string)=>{const blocked=bookedTimes?.some((t:string)=>t.startsWith(x));return <option key={x} value={x} disabled={blocked}>{x}{blocked?" · BOOKED":""}</option>})}</select></label><label>Duration<select value={Math.min(duration,maxHours||1)} onChange={(e:any)=>setDuration(Number(e.target.value))} disabled={!maxHours}>{Array.from({length:Math.max(1,maxHours||0)},(_,i)=>i+1).map(h=><option key={h} value={h}>{h} hour{h===1?"":"s"} · ends {addHours(value,h)}</option>)}</select></label><div className="endTime"><span>End time</span><strong>{addHours(value,Math.min(duration,maxHours||1))}</strong></div><div className="timeNote"><Timer/> From {value}, you can book up to <b>{maxHours||0} hour{maxHours===1?"":"s"}</b> until 7:00 PM or the next booked time. The selected hours repeat on each booked day.</div></div>}
