import React,{useState} from "react";
import {CalendarDays,Clock3,Lock,MessageCircle,Timer,UserPlus,Phone,Monitor,Building2,Mic2,Users,CheckCircle2} from "lucide-react";
import {Space,desks,confStarts,meetingStarts,podStarts,addHours,BUSINESS_START,BUSINESS_END} from "./types";
import conferenceImage from "../assets/conference-2.webp";import podcastImage from "../assets/podcast.webp";
import "./booking.css";import "./ui-fixes.css";

const deskLayout:Array<string|null>=[
 "D04","D03","D02","D01",
 "D05","D06","D07","D08",
 "D11","D10","D09",null,
 "D12","D13","D14","D15",
 "D19","D18","D17","D16",
 "D20","D21","D22",null
];
const deskById=Object.fromEntries(desks.map(d=>[d.id,d]));

export default function Booking(p:any){
 const selectedSeats=p.selectedSeats||[];const [profileOpen,setProfileOpen]=useState(false);const [profile,setProfile]=useState({mobile:p.phoneNumber||"",gender:p.user?.gender||"",dob:p.user?.dob||"",profession:p.user?.profession||""});
 const start=p.space==="conference"?p.conf:p.space==="meeting"?p.meeting:p.pod;const duration=p.space==="conference"?5:p.space==="meeting"?p.meetingDuration:1;const end=addHours(start,duration);
 const isTimed=p.space!=="desk"&&p.space!=="cubicle";const isValidHours=!isTimed|| (start>=BUSINESS_START&&end<=BUSINESS_END);const openCalendar=()=>{const el=document.getElementById("booking-date") as HTMLInputElement|null;try{el?.showPicker?.()}catch{el?.focus?.()}};
 const toggleSeat=(id:string)=>{if(p.booked.includes(`seat-${id}`)||p.booked.includes(`desk-${id}`))return;const next=selectedSeats.includes(id)?selectedSeats.filter((x:string)=>x!==id):[...selectedSeats,id];p.setSelectedSeats(next)};
 const submit=()=>{if(!isValidHours)return;setProfile({mobile:p.phoneNumber||profile.mobile,gender:profile.gender,dob:profile.dob,profession:profile.profession});setProfileOpen(true)};
 const spaceTitle=p.space==="desk"||p.space==="cubicle"?"Desk":p.space==="meeting"?"Meeting Room":p.space==="conference"?"Conference Room":"Creator Studio";
 return <main className="page bookingPage"><div className="bookingIntro"><div><span className="eyebrow">MAKE A RESERVATION</span><h2>{p.staffBooking?"Book for a customer":"Choose your workspace."}</h2><p>Working hours are <strong>9:00 AM–7:00 PM</strong> for desks, meeting room, conference room and creator studio. Bookings stay inside these hours.</p></div>{p.staff&&<div className="staffMode"><span>Staff booking</span><div className="staffToggle"><button className={!p.staffBooking?"active":""} onClick={()=>p.setStaffBooking(false)}>My booking</button><button className={p.staffBooking?"active":""} onClick={()=>p.setStaffBooking(true)}><UserPlus size={15}/> Walk-in customer</button></div></div>}{p.staffBooking&&<div className="customerBox"><div className="customerFields"><label>Customer email address<input required type="email" placeholder="customer@gmail.com" value={p.customerEmail} onChange={(e:any)=>p.setCustomerEmail(e.target.value)}/></label><label><span>Customer mobile number <b>*</b></span><div className="phoneInput"><Phone size={16}/><input required type="tel" placeholder="+91 98765 43210" value={p.phoneNumber} onChange={(e:any)=>p.setPhoneNumber(e.target.value)}/></div></label></div><small>We use the email to identify the customer and the phone to contact them.</small></div>}{!p.staffBooking&&<div className="customerBox userContact"><label><span>Your mobile number <b>*</b></span><div className="phoneInput"><Phone size={16}/><input required type="tel" placeholder="+91 98765 43210" value={p.phoneNumber} onChange={(e:any)=>p.setPhoneNumber(e.target.value)}/></div></label><small>Your Google name is fetched automatically. Extra profile details are collected only when you submit the booking.</small></div>}</div>
 <div className="bookingGrid"><section className="panel bookingPanel"><button type="button" className="dateField" onClick={openCalendar}><span className="dateIcon"><CalendarDays size={20}/></span><span className="dateCopy"><span className="dateLabel">BOOKING DATE</span><strong>{p.date}</strong><small>Choose a date from the calendar</small></span><input id="booking-date" aria-label="Select booking date" type="date" min={new Date().toISOString().slice(0,10)} value={p.date} onChange={(e:any)=>p.setDate(e.target.value)}/></button>
 <div className="tabs">{([["desk","Desks"],["meeting","Meeting Room"],["conference","Conference"],["podcast","Creator Studio"]] as [Space,string][]).map(([s,l])=><button key={s} className={p.space===s||((s==="desk")&&p.space==="cubicle")?"active":""} onClick={()=>{p.setSpace(s);if(s!=="desk")p.setSelectedSeats([])}}>{l}</button>)}</div>
 {(p.space==="desk"||p.space==="cubicle")&&<><div className="workingHoursBanner"><Clock3/> <b>Open 9:00 AM–7:00 PM</b><span>Desk booking = full business day</span></div><div className="panelHead"><div><h3>22 desk floor map</h3><small>Arranged to match the real desk layout. Premium = lockable drawer.</small></div><b>₹{p.prices.desk_basic} regular · ₹{p.prices.desk_premium} premium</b></div><div className="deskBulkNote">{selectedSeats.length?`${selectedSeats.length} desk${selectedSeats.length===1?"":"s"} selected`:"Select desks from the floor plan"}{selectedSeats.length>5&&<span>10% bulk discount applied</span>}</div><div className="seatGrid redesignedDeskGrid floorPlanGrid">{deskLayout.map((id,idx)=>{if(!id)return <div key={`pillar-${idx}`} className="pillarGap" aria-label="Structural pillar space"><span>PILLAR</span></div>;const s=deskById[id];const b=p.booked.includes(`desk-${s.id}`)||p.booked.includes(`seat-${s.id}`),sel=selectedSeats.includes(s.id);const price=p.deskPrices?.[s.id]??(s.premium?p.prices.desk_premium:p.prices.desk_basic);return <button key={s.id} disabled={b} className={`seat deskCard ${b?"booked":""} ${sel?"selected":""} ${s.premium?"premium":""}`} onClick={()=>toggleSeat(s.id)}><Monitor size={31}/><strong>{s.number}</strong><b>₹{price}/day</b><small>{b?"BOOKED":s.premium?"PREMIUM · DRAWER + LOCK":"REGULAR DESK"}</small>{sel&&<span className="deskCheck"><CheckCircle2/></span>}</button>})}</div><div className="floorLegend"><span><i className="legendDesk"/> Desk</span><span><i className="legendPremium"/> Premium / drawer + lock</span><span><i className="legendPillar"/> Pillar / blank space</span></div></>}
 {p.space==="meeting"&&<TimeRoom image={null} icon={<Users/>} title="Meeting Room" capacity="8 seats" price={p.prices.meeting_hourly} starts={meetingStarts} value={p.meeting} set={p.setMeeting} duration={p.meetingDuration} setDuration={p.setMeetingDuration} end={end} note="8-seater · ₹600/hour · book multiple hours · AC · Wi-Fi · power" working="9:00 AM–7:00 PM"/>}
 {p.space==="conference"&&<TimeRoom image={conferenceImage} icon={<Building2/>} title="Conference Room" capacity="18 seats" price={p.prices.conference_slot} starts={confStarts} value={p.conf} set={p.setConf} duration={5} end={end} note="18-seater · 5-hour block · U-shaped table · AC · Wi-Fi · power modules" working="9:00 AM–7:00 PM" fixed/>}
 {p.space==="podcast"&&<TimeRoom image={podcastImage} icon={<Mic2/>} title="Creator Studio" capacity="Creator room" price={p.prices.podcast_hourly} starts={podStarts} value={p.pod} set={p.setPod} duration={1} end={end} note="Hourly · lights · microphones · stands · everything included · camera not provided" working="9:00 AM–7:00 PM"/>}
 </section><aside className="summary panel"><span className="eyebrow">BOOKING SUMMARY</span><h3>{selectedSeats.length?`${selectedSeats.length} Desk${selectedSeats.length===1?"":"s"} Selected`:spaceTitle}</h3><p><CalendarDays/> {p.date}</p>{isTimed&&<p><Clock3/> {start}–{end} · {duration} hr{duration===1?"":"s"}</p>}{!isTimed&&selectedSeats.length>0&&<p><Monitor/> {selectedSeats.join(", ")}</p>}<p><Clock3/> Business hours: 9:00 AM–7:00 PM</p><hr/><div className="money"><span>{!isTimed?`${selectedSeats.length} desk price`:`${duration} hour${duration===1?"":"s"}`}</span><b>₹{p.base}</b></div>{p.bulkDiscount>0&&<div className="money good"><span>5+ desk discount (10%)</span><b>−₹{p.bulkDiscount}</b></div>}{p.offerDiscount>0&&<div className="money good"><span>Offer discount</span><b>−₹{p.offerDiscount}</b></div>}<div className="money total"><span>Total to request</span><strong>₹{p.total}</strong></div>{p.offers[0]&&<div className="offerMini"><b>{p.offers[0].title}</b><small>{p.offers[0].type==="percent"?`${p.offers[0].value}% OFF`:`₹${p.offers[0].value} OFF`}</small></div>}<div className="lock"><Lock/> {p.staffBooking?"Staff booking confirms immediately.":"Your selection is held for 15 minutes after request submission."}</div><button className="whatsapp" onClick={submit} disabled={(!selectedSeats.length&&!isTimed)||!isValidHours}>{p.staffBooking?"Confirm customer booking":"Request on WhatsApp"}<MessageCircle/></button>{!isValidHours&&<small className="error">This time falls outside the 9:00 AM–7:00 PM business day.</small>}</aside></div>
 {profileOpen&&<ProfileModal profile={profile} setProfile={setProfile} name={p.user?.displayName||p.user?.email?.split("@")[0]||"Coworx Member"} onClose={()=>setProfileOpen(false)} onContinue={()=>{setProfileOpen(false);p.setPhoneNumber(profile.mobile);p.book(profile)}}/>}</main>;
}
function ProfileModal({profile,setProfile,name,onClose,onContinue}:any){return <div className="modalBackdrop"><div className="modalCard"><div className="modalHead"><div><span className="eyebrow">CUSTOMER DETAILS</span><h3>Complete your booking</h3></div><button onClick={onClose}>×</button></div><div className="identityBox"><strong>{name}</strong><span>Name fetched from your Google account</span></div><div className="formGrid compact"><label>Mobile number <b>*</b><input required type="tel" value={profile.mobile} onChange={e=>setProfile({...profile,mobile:e.target.value})}/></label><label>Gender<select value={profile.gender} onChange={e=>setProfile({...profile,gender:e.target.value})}><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option><option>Prefer not to say</option></select></label><label>Date of birth<input type="date" value={profile.dob} onChange={e=>setProfile({...profile,dob:e.target.value})}/></label><label>Profession<input placeholder="Designer, student, founder…" value={profile.profession} onChange={e=>setProfile({...profile,profession:e.target.value})}/></label></div><small className="muted">Your profile details are stored with your Coworx account and are not added to the WhatsApp message.</small><div className="modalFooter"><button className="ghost" onClick={onClose}>Back</button><button className="primary" onClick={onContinue}>Continue to WhatsApp <MessageCircle/></button></div></div></div>}
function TimeRoom({image,icon,title,capacity,price,starts,value,set,duration,setDuration,end,note,working,fixed}:any){return <div className="room"><div className="roomVisual">{image?<img src={image} alt={title}/>:<div className="roomIconHero">{icon}</div>}</div><div className="workingHoursBanner"><Clock3/> <b>Open {working}</b><span>{capacity}</span></div><div className="panelHead"><div><h3>{title}</h3><small>{note}</small></div><b>₹{price} / {fixed?"5 hrs":"hour"}</b></div><label>Start time<select value={value} onChange={(e:any)=>set(e.target.value)}>{starts.map((x:string)=><option key={x} value={x}>{x}</option>)}</select></label>{!fixed&&setDuration&&<label>Duration<select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[1,2,3,4,5,6,7,8,9,10].map(h=><option key={h} value={h}>{h} hour{h===1?"":"s"}</option>)}</select></label>}<div className="endTime"><span>End time</span><strong>{end}</strong></div><div className="timeNote"><Timer/> Booking must finish by 7:00 PM.</div></div>}
