import { useEffect, useState } from "react";
import { Download, WalletCards } from "lucide-react";
import { collectionTotals, correctPaymentMethod, downloadReceipt, emptyTender, saveHandover, watchHandovers, watchPayments } from "../lib/finance";
import { balance, money } from "../lib/business";
import { localToday } from "./types";
import PaymentDialog from "../components/PaymentDialog";
import Dialog from "../components/Dialog";
import { DatePicker } from "./DatePicker";
import { StaffServiceOrders } from "../components/ServiceOrders";
import InvoiceExport from "../components/InvoiceExport";
export default function Collections({bookings,can,company,onFlash}:any) {
  const [payments,setPayments]=useState<any[]>([]),[handovers,setHandovers]=useState<any[]>([]),[date,setDate]=useState(localToday()),[loading,setLoading]=useState(true),[error,setError]=useState(""),[booking,setBooking]=useState<any>(null),[closing,setClosing]=useState(false),[opening,setOpening]=useState(0),[counted,setCounted]=useState(0),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[correction,setCorrection]=useState<any>(null),[reason,setReason]=useState(""),[corrected,setCorrected]=useState<any>(emptyTender());
  useEffect(()=>{const a=watchPayments(r=>{setPayments(r);setLoading(false);},e=>{setError(e.message);setLoading(false);}),b=watchHandovers(setHandovers,e=>setError(e.message));return()=>{a();b();};},[]);
  const rows=payments.filter(p=>p.date===date), totals=collectionTotals(rows);
  const last=handovers.filter(h=>h.date===date).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0))[0];
  const shift=rows.filter(p=>(p.createdAt?.toMillis?.()||0)>(last?.createdAt?.toMillis?.()||0)),shiftTotals=collectionTotals(shift),expected=Math.round((opening+shiftTotals.cash)*100)/100;
  const pending=bookings.filter((b:any)=>(b.status==="Pending"&&b.expiresAt?.toMillis()>Date.now() || b.status==="Confirmed")&&balance(b)>0);
  const run=async(fn:()=>Promise<any>,message:string)=>{setBusy(true);setError("");try{await fn();onFlash(message);setClosing(false);setCorrection(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  const beginCorrection=(p:any)=>{setCorrection(p);setReason("");setCorrected({cash:Number(p.cashAmount||0),upi:Number(p.upiAmount||0),other:Number(p.otherAmount||0),reference:String(p.reference||"")});setError("");};
  return <section className="workspacePage"><div className="pageHeading"><div><span className="eyebrow">PAYMENTS & HANDOVER</span><h1>Daily collections</h1><p>Cash, UPI and other payments for the selected date. Original receipts never change; admin corrections are recorded separately.</p></div><div className="buttonRow"><DatePicker label="Collection date" value={date} max={localToday()} onChange={setDate}/><button className="primary" disabled={date!==localToday()} onClick={()=>{setOpening(Number(last?.countedCash||0));setCounted(0);setNote("");setClosing(true);}}>Close shift</button></div></div>
    {error&&<p className="inlineError" role="alert">{error}</p>}
    <div className="collectionMetrics">{[["Cash collected",totals.cash],["UPI collected",totals.upi],["Other",totals.other],["Net collected",totals.net]].map(([label,n])=><div className="surface" key={String(label)}><small>{label} · {date}</small><strong>{money(Number(n))}</strong></div>)}</div>
    {can("revenueView")&&<InvoiceExport bookings={bookings} company={company} onFlash={onFlash}/>} 
    <StaffServiceOrders can={can} onFlash={onFlash}/>
    {can("paymentsCollect")&&<section className="surface"><div className="sectionHeading"><h3>Collect payment</h3><span>{pending.length} awaiting full payment</span></div><div className="guestList">{pending.slice(0,20).map((b:any)=><button className="guestRow" key={b.id} onClick={()=>setBooking(b)}><WalletCards/><span><b>{b.customerName||b.customerEmail}</b><small>{b.label} · Full advance required before confirmation</small></span><strong>{money(balance(b))}</strong></button>)}{!pending.length&&<p>No outstanding active bookings.</p>}</div></section>}
    <section className="surface"><h3>Payment register</h3>{loading?<div className="skeleton" style={{height:180}}/>:<div className="tableScroll"><table className="dataTable"><thead><tr><th>Receipt / customer</th><th>Type</th><th>Cash</th><th>UPI</th><th>Other</th><th>Total</th><th>Actions</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.customerName}</b><small>{p.receiptNumber} · {p.createdAt?.toDate?.().toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata",hour:"numeric",minute:"2-digit"})||"Saving time…"}</small><small>{p.reference}</small>{p.reason&&<small>{p.reason}</small>}</td><td>{p.kind}</td><td>{money(p.cashAmount)}</td><td>{money(p.upiAmount)}</td><td>{money(p.otherAmount)}</td><td>{p.kind==="Refund"||p.kind==="Correction"?"−":""}{money(p.amount)}</td><td><button className="ghost" onClick={()=>downloadReceipt(p,company).catch(e=>setError(e.message))}><Download size={16}/> Receipt</button>{can("paymentsCorrect")&&p.kind==="Collection"&&!payments.some(x=>x.kind==="Method Correction"&&x.originalPaymentId===p.id)&&<button className="textButton" onClick={()=>beginCorrection(p)}>Correct payment mode</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="emptyState">No payment entries for this date. Earlier bookings may predate the receipt register.</p>}</div>}</section>
    <section className="surface"><h3>Shift handovers</h3>{handovers.filter(h=>h.date===date).map(h=><div className="handoverRow" key={h.id}><b>Counted {money(h.countedCash)} · Expected {money(h.expectedCash)}</b><span>Difference {money(h.difference)} · {h.createdAt?.toDate?.().toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata"})}</span><p>{h.note||"No handover note"}</p></div>)}{!last&&<p>No shift closed yet.</p>}</section>
    {booking&&<PaymentDialog booking={booking} canDiscount={can("bookingsDiscount")} onClose={()=>setBooking(null)} onSaved={(r:string)=>{setBooking(null);onFlash(`Payment saved · ${r}`);}}/>}
    {closing&&<Dialog title="Cash & shift handover" onClose={()=>!busy&&setClosing(false)}><p>Cash movement since {last?"the last handover":"the start of today"}. One shared reception till.</p><div className="fieldGrid"><label>Opening cash ₹<input type="number" min="0" step="0.01" value={opening} onChange={e=>setOpening(Number(e.target.value))}/></label><label>Cash physically counted ₹<input type="number" min="0" step="0.01" value={counted} onChange={e=>setCounted(Number(e.target.value))}/></label></div><p>Net cash movement: {money(shiftTotals.cash)} · Expected: <b>{money(expected)}</b> · Difference: <b>{money(counted-expected)}</b></p><label>Handover note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain differences and anything the next shift needs to know"/></label>{error&&<p className="inlineError">{error}</p>}<div className="formActions"><button className="primary" disabled={busy||counted!==expected&&!note.trim()} onClick={()=>run(()=>saveHandover(date,opening,counted,expected,note),"Shift handover saved.")}>{busy?"Saving…":"Save handover"}</button></div></Dialog>}
    {correction&&<Dialog title="Correct payment method" onClose={()=>!busy&&setCorrection(null)}><p><b>Admin-only critical correction.</b> Use this only when the money was received correctly but was recorded under the wrong mode, for example Cash instead of UPI. The customer's paid amount will not change and the original receipt will remain in the audit trail.</p><p>Original receipt: <b>{correction.receiptNumber}</b> · {money(correction.amount)}</p><div className="fieldGrid"><label>Cash ₹<input type="number" min="0" step="0.01" value={corrected.cash} onChange={e=>setCorrected({...corrected,cash:Number(e.target.value)})}/></label><label>UPI ₹<input type="number" min="0" step="0.01" value={corrected.upi} onChange={e=>setCorrected({...corrected,upi:Number(e.target.value)})}/></label><label>Other ₹<input type="number" min="0" step="0.01" value={corrected.other} onChange={e=>setCorrected({...corrected,other:Number(e.target.value)})}/></label><label>UPI / other reference<input value={corrected.reference} onChange={e=>setCorrected({...corrected,reference:e.target.value})}/></label></div><label>Reason for correction<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Example: Manager selected Cash, but customer actually paid by UPI"/></label>{error&&<p className="inlineError">{error}</p>}<button className="primary" disabled={busy||!reason.trim()} onClick={()=>run(()=>correctPaymentMethod(correction.id,corrected,reason),"Payment method corrected. Customer paid balance is unchanged.")}>{busy?"Saving…":"Save admin correction"}</button></Dialog>}
  </section>;
}
