import { setCustomerBlock } from "../lib/firestore";
import { useEffect, useState } from "react";
import { doc, updateDoc } from "firebase/firestore";
import { db } from "../firebase";
import { Search } from "lucide-react";
import { watchPayments, downloadReceipt } from "../lib/finance";
import { balance, money } from "../lib/business";
import { localToday, addDays } from "./types";
import CustomerPicker from "../components/CustomerPicker";
export default function CustomerDirectory({users,bookings,user,can,company,onFlash,initialQuery="",bookCustomer}:any) {
  const [search,setSearch]=useState(initialQuery),[selected,setSelected]=useState<any>(null),[draft,setDraft]=useState<any>({}),[receipts,setReceipts]=useState<any[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false),[blockReason,setBlockReason]=useState("");
  useEffect(()=>{if(!can("collectionsView"))return;return watchPayments(setReceipts,e=>setError(e.message));},[can]);
  useEffect(()=>{if(selected){const current=users.find((u:any)=>(u.uid||u.id)===(selected.uid||selected.id));if(current)setSelected(current);}},[users]);
  const choose=(u:any)=>{setSelected(u);setBlockReason(u.blockedReason||"");setDraft({name:u.name||"",phone:u.phone||u.mobile||"",company:u.company||"",gstNumber:u.gstNumber||"",billingAddress:u.billingAddress||"",customerNotes:u.customerNotes||"",profession:u.profession||"",dob:u.dob||"",gender:u.gender||"",preferredDesk:u.preferredDesk||"",vip:!!u.vip,reminderPreferences:{booking:u.reminderPreferences?.booking!==false,expiry:u.reminderPreferences?.expiry!==false,balance:u.reminderPreferences?.balance!==false}});setError("");};
  const own=(b:any)=>selected&&(b.userId===(selected.uid||selected.id)||b.customerEmail===selected.email),history=bookings.filter(own),payments=receipts.filter(own);
  const save=async()=>{setBusy(true);try{await updateDoc(doc(db,"users",selected.uid||selected.id),draft);onFlash("Customer details saved.");}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  const reminders=bookings.filter((b:any)=>b.status==="Confirmed").flatMap((b:any)=>{const customer=users.find((u:any)=>u.uid===b.userId||u.email===b.customerEmail),prefs=customer?.reminderPreferences||{};const items:string[]=[];if(prefs.balance!==false&&balance(b)>0&&b.balanceDueDate<=addDays(localToday(),2))items.push(`${b.customerName}: ${money(balance(b))} balance due ${b.balanceDueDate}`);if(prefs.expiry!==false&&b.passDays&&b.endDate>=localToday()&&b.endDate<=addDays(localToday(),3))items.push(`${b.customerName}: pass ends ${b.endDate}`);return items;});
  return <section className="workspacePage"><div className="pageHeading"><div><span className="eyebrow">PEOPLE & HISTORY</span><h1>Customers</h1><p>Profiles, billing details, bookings, pass balances and receipts.</p></div>{can("customersCreate")&&<button className="primary" onClick={()=>setCreating(!creating)}>Add customer</button>}</div>
    {creating&&<CustomerPicker users={users} selected={null} onSelect={(u:any)=>{choose(u);setCreating(false);}} user={user} canCreate={can("customersCreate")}/>}
    {reminders.length>0&&<details className="surface"><summary>Follow-ups · {reminders.length}</summary>{reminders.map((r:string,i:number)=><p key={i}>{r}</p>)}<small>Follow-ups respect the customer’s reminder preferences. No messages are sent automatically.</small></details>}
    <div className="customerWorkspace"><section className="surface customerList"><label className="searchInput"><Search size={18}/><input placeholder="Name, phone or email" aria-label="Search customers" value={search} onChange={e=>setSearch(e.target.value)}/></label>{users.filter((u:any)=>[u.name,u.email,u.phone].join(" ").toLowerCase().includes(search.toLowerCase())).map((u:any)=><button className={`customerListRow ${(selected?.uid||selected?.id)===(u.uid||u.id)?"active":""}`} key={u.uid||u.id} onClick={()=>choose(u)}><b>{u.name||u.email}</b><small>{u.phone||u.email}</small>{u.blocked&&<span className="statePill warn">Blocked</span>}</button>)}</section>
    <section className="surface">{!selected?<div className="emptyState"><h3>Select a customer</h3><p>Their details and history will appear here.</p></div>:<><div className="sectionHeading"><div><h2>{selected.name}</h2><p>{selected.email}</p></div>{can("bookingsCreate")&&<button className="primary" disabled={!!selected.blocked} onClick={()=>bookCustomer(selected)}>Book for customer</button>}</div><div className="fieldGrid">{[["name","Full name"],["phone","Mobile"],["company","Company name"],["gstNumber","Customer GST number"],["billingAddress","Billing address"],["customerNotes","Staff notes"],["profession","Profession"],["dob","Date of birth"],["gender","Gender"],["preferredDesk","Preferred desk"]].map(([key,label])=><label key={key}>{label}<input value={draft[key]||""} disabled={!can("customersEdit")} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}</div><label className="checkLabel"><input type="checkbox" checked={!!draft.vip} disabled={!can("customersEdit")} onChange={e=>setDraft({...draft,vip:e.target.checked})}/>VIP customer</label><div className="preferenceRow">{[["booking","Booking reminders"],["expiry","Pass expiry reminders"],["balance","Payment reminders"]].map(([key,label])=><label className="checkLabel" key={key}><input type="checkbox" disabled={!can("customersEdit")} checked={draft.reminderPreferences?.[key]!==false} onChange={e=>setDraft({...draft,reminderPreferences:{...draft.reminderPreferences,[key]:e.target.checked}})}/>{label}</label>)}</div>{can("customersEdit")&&<button className="primary" disabled={busy} onClick={save}>{busy?"Saving…":"Save customer details"}</button>}{error&&<p className="inlineError">{error}</p>}
    {can("customersBlock")&&<details><summary>{selected.blocked?"Customer is blocked":"Booking access"}</summary><label>Reason<input value={blockReason} onChange={e=>setBlockReason(e.target.value)}/></label><button className="ghost" disabled={busy||!selected.blocked&&!blockReason.trim()} onClick={async()=>{setBusy(true);try{await setCustomerBlock(selected.uid||selected.id,!selected.blocked,blockReason,user.uid,user.email);onFlash("Customer access updated.");}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{selected.blocked?"Unblock customer":"Block new bookings"}</button></details>}
    <h3>Bookings & passes</h3><p>Outstanding active balance: <b>{money(history.filter((b:any)=>b.status==="Confirmed").reduce((n:number,b:any)=>n+balance(b),0))}</b></p><div className="historyList">{history.map((b:any)=><div key={b.id}><b>{b.label}</b><span>{b.date} → {b.endDate||b.date} · {b.status}</span><small>{money(b.total)} · Received {money(b.paymentReceived)}{b.passDays?` · ${Number(b.rescheduleAllowance)-Number(b.rescheduleUsed||0)} reschedules left`:""}</small></div>)}</div><h3>Payment history</h3>{payments.map(p=><div className="historyReceipt" key={p.id}><span>{p.date} · {p.kind} · {money(p.amount)}</span><button className="ghost" onClick={()=>downloadReceipt(p,company).catch(e=>setError(e.message))}>Receipt</button></div>)}{!payments.length&&<p>No receipt entries available.</p>}</> }</section></div>
  </section>;
}
