import {useEffect,useMemo,useState} from "react";
import {CalendarDays,CheckCircle2,Clock3,Copy,Download,ExternalLink,FileText,Gift,LogIn,LogOut,MessageCircle,Phone,Plus,RotateCcw,Settings,ShieldCheck,Tag,TrendingUp,UserMinus,UserPlus,Users,WalletCards,Wifi,X} from "lucide-react";
import {ADMIN_EMAILS,Booking,Offer} from "./types";
import {watchMembershipPlans,extendBooking} from "../lib/firestore";
import {downloadInvoice} from "../lib/invoice";
import "./ops.css";import "./ui-fixes.css";import "./booking-enhancements.css";
const wa=(phone:string)=>{const d=(phone||"").replace(/\D/g,"");return d.length===10?`91${d}`:d};
const activePending=(b:any)=>b.status==="Pending"&&(b.expiresAt?.toMillis?.()||0)>Date.now();
const remainingMs=(b:any)=>Math.max(0,(b.expiresAt?.toMillis?.()||0)-Date.now());
const isToday=(d:string)=>{const n=new Date();const x=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,"0")}-${String(n.getDate()).padStart(2,"0")}`;return d===x};
const bookingWhatsApp=(b:any)=>{const phone=wa(b.customerPhone||"");if(!phone)return "#";const text=`Hello, this is ${window._coworx_company?.name||"Coworx Central"} regarding your ${b.label} booking on ${b.date}${b.start?` from ${b.start} to ${b.end}`:""}.`;return `https://wa.me/${phone}?text=${encodeURIComponent(text)}`};
// updated printReceipt to use company details if available. prefer downloadInvoice for PDF
const printReceipt=(b:any,company?:any)=>{const w=window.open("","_blank","width=720,height=760");if(!w)return;const name=company?.name||window._coworx_company?.name||"Coworx Central";const address=company?.address||window._coworx_company?.address||"Solapur City · Receipt";const phone=company?.phone||window._coworx_company?.phone||"";const headerTitle=company?.gstNumber||window._coworx_company?.gstNumber?"GST INVOICE":"RECEIPT";w.document.write(`<html><head><title>${b.invoiceNumber||"Coworx receipt"}</title><style>body{font-family:Arial,sans-serif;padding:36px;line-height:1.5;color:#151515}h1{margin-bottom:4px}small{color:#666}.box{border:1px solid #ddd;border-radius:12px;padding:18px;margin:22px 0}.row{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #eee}.total{font-size:20px;font-weight:800;border:0}</style></head><body><h1>${name}</h1><small>${address}${phone?` · ${phone}`:""}</small><div class="box"><div class="row"><span>Invoice</span><b>${b.invoiceNumber||b.id.slice(0,8)}</b></div><div class="row"><span>Customer</span><b>${b.customerName||b.customerEmail||"Customer"}</b></div><div class="row"><span>Service</span><b>${b.label}</b></div><div class="row"><span>Date</span><b>${b.date}${b.endDate&&b.endDate!==b.date?` → ${b.endDate}`:""}</b></div>${b.start?`<div class="row"><span>Time</span><b>${b.start}–${b.end}</b></div>`:""}<div class="row"><span>Payment</span><b>${b.paymentMethod||"Other"}</b></div><div class="row total"><span>Total</span><b>₹${b.total||0}</b></div></div><p>Working hours: 9:00 AM–7:00 PM. Thank you for choosing ${name}.</p><script>window.print()</script></body></html>`);w.document.close()};
export function LoginPage({onLogin,error}:{onLogin:()=>void;error:string}){return <main className="login"><section className="loginCard"><span className="brandMark">C</span><span className="eyebrow">COWORX CENTRAL</span><h2>Sign in with Google</h2><p>Booking, My Bookings, memberships and offers require Google sign-in.</p><button className="primary" onClick={onLogin}><LogIn/> Continue with Google</button>{error&&<small className="error">{error}</small>}</section></main>}
export function Account({bookings,staff=false,onCancel,onCheckIn,onCheckOut,wifi,company}:{bookings:Booking[];staff?:boolean;onCancel?:(id:string)=>void;onCheckIn?:(id:string)=>void;onCheckOut?:(id:string)=>void;wifi:any;company:any}){/*...component code omitted for brevity...*/return <></>}