export type Role = "User" | "Manager" | "Admin";
export type Space = "desk" | "meeting" | "conference" | "podcast" | "cubicle";
export type OfferType = "percent" | "fixed";
export type TargetType = "all" | "email";
export type BookingStatus = "Pending" | "Confirmed" | "Expired" | "Cancelled";
export type AppUser = {uid:string;name:string;email:string;photoURL?:string;role:Role;phone?:string;gender?:string;dob?:string;profession?:string};
export type Offer = {id:string;title:string;description:string;type:OfferType;value:number;targetType:TargetType;targetEmail?:string;active:boolean};
export type Booking = {id:string;userId:string;userEmail:string;customerName?:string;customerEmail?:string;customerPhone?:string;inventoryId:string;inventoryIds?:string[];lockIds?:string[];space:Space;label:string;date:string;endDate?:string;days?:number;start?:string;end?:string;durationHours?:number;base:number;discount:number;staffDiscount?:number;total:number;offerId?:string|null;status:BookingStatus;walkIn?:boolean;createdByRole?:Role|string;paymentMethod?:"UPI"|"Cash"|"Other";paymentRef?:string;paymentReceived?:number;confirmedBy?:string;confirmedAt?:any;expiresAt?:any;createdAt?:any;checkedInAt?:any;checkedOutAt?:any;revokedBy?:string;revokedAt?:any};
export const ADMIN_EMAIL="vsshegur@gmail.com";
export const ADMIN_EMAILS=["vsshegur@gmail.com","navingaddam2@gmail.com"];
export const WA="919970836509";
export const BUSINESS_START="09:00";
export const BUSINESS_END="19:00";
export const DESK_COUNT=22;
export const DEFAULT_PRICING={desk_basic:200,desk_premium:250,meeting_hourly:600,conference_hourly:500,podcast_hourly:200};
const premiumDeskNumbers=[2,3,9,15,22];
export const desks=Array.from({length:DESK_COUNT},(_,i)=>{const number=i+1;return{id:`D${String(number).padStart(2,"0")}`,number,premium:premiumDeskNumbers.includes(number)}});
export const seats=desks;
export const confStarts=["09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00"];
export const meetingStarts=confStarts;
export const podStarts=confStarts;
export const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
export const today=localToday;
export const addHours=(t:string,h:number)=>{const [hh,mm]=t.split(":").map(Number),n=hh*60+mm+h*60;return `${String(Math.floor(n/60)%24).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`};
export const addDays=(iso:string,n:number)=>{const d=new Date(`${iso}T00:00:00`);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
export const dateSpan=(start:string,end:string)=>{if(end<start)return[];const out:string[]=[];for(let i=0;i<370;i++){const d=addDays(start,i);out.push(d);if(d===end)break;}return out};
export const withinBusinessHours=(start:string,end:string)=>start>=BUSINESS_START&&end<=BUSINESS_END&&start<end;
