import { useEffect, useMemo, useState } from "react";
import { Mail, MessageCircle, Plus, Search, Flame, Snowflake, AlertTriangle } from "lucide-react";
import { createEnquiry, updateEnquiry, watchEnquiries } from "../lib/firestore";
import { normalizePhone, validEmail, validPhone } from "../lib/customer";

const wa=(phone:string)=>`91${normalizePhone(phone)}`;
const message=(en:any)=>`Hello ${en.name || "there"}, this is Coworx Central. Thank you for your enquiry about ${en.interest || "our workspace"}. How can we help you with your workspace requirement?`;

export default function EnquiryCRM({actorUid,onFlash}:any){
  const [items,setItems]=useState<any[]>([]),[query,setQuery]=useState(""),[form,setForm]=useState<any>({name:"",phone:"",email:"",interest:"desk",notes:"",temperature:"Warm",priority:"Normal",status:"New"}),[busy,setBusy]=useState(false);
  useEffect(()=>watchEnquiries(setItems,e=>onFlash(e.message)),[]);
  const filtered=useMemo(()=>items.filter(en=>!query||[en.name,en.email,en.phone,en.interest,en.notes,en.temperature,en.priority,en.status].join(" ").toLowerCase().includes(query.toLowerCase())),[items,query]);
  const save=async()=>{if(!form.name.trim())return onFlash("Enter enquiry name.");if(form.phone&&!validPhone(form.phone))return onFlash("Enter a valid 10-digit Indian mobile number starting with 6, 7, 8 or 9.");if(form.email&&!validEmail(form.email))return onFlash("Enter a valid email.");setBusy(true);try{await createEnquiry({...form,name:form.name.trim(),source:"Staff"},actorUid);setForm({name:"",phone:"",email:"",interest:"desk",notes:"",temperature:"Warm",priority:"Normal",status:"New"});onFlash("Enquiry saved.");}catch(e:any){onFlash(e.message);}finally{setBusy(false);}};
  const patch=async(en:any,data:any)=>{try{await updateEnquiry(en.id,data,actorUid);onFlash("Enquiry updated.");}catch(e:any){onFlash(e.message);}};
  return <section className="opsPanel enquiryCrm"><div className="panelHead"><div><span className="eyebrow">ENQUIRY CRM</span><h3>Leads & follow-up</h3><small>Keep contact details, temperature, urgency and follow-up status together.</small></div><Search/></div>
    <div className="stackForm enquiryCreate"><div className="fieldGrid"><label>Name *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Mobile<input inputMode="numeric" maxLength={10} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value.replace(/\D/g,"").slice(0,10)})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Interest<select value={form.interest} onChange={e=>setForm({...form,interest:e.target.value})}><option value="desk">Desk</option><option value="meeting">Meeting Room</option><option value="conference">Conference Room</option><option value="podcast">Creator Studio</option><option value="other">Other</option></select></label><label>Lead type<select value={form.temperature} onChange={e=>setForm({...form,temperature:e.target.value})}><option>Cold</option><option>Warm</option><option>Hot</option></select></label><label>Attention<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Normal</option><option>Urgent</option></select></label></div><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Requirement, budget, preferred dates, next follow-up…"/></label><button className="primary" disabled={busy} onClick={save}><Plus size={17}/>{busy?"Saving…":"Add enquiry"}</button></div>
    <label className="searchInput"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search enquiry, phone, email, type or status"/></label>
    <div className="catalogList enquiryList">{filtered.map(en=><article className={`catalogItem enquiryCard ${en.priority==="Urgent"?"urgent":""}`} key={en.id}><div className="enquiryIdentity"><b>{en.name}</b><small>{en.phone||"No phone"} · {en.email||"No email"}</small><span>{en.interest||"General"}{en.notes?` · ${en.notes}`:""}</span><div className="enquiryTags"><span>{en.temperature==="Hot"?<Flame size={13}/>:en.temperature==="Cold"?<Snowflake size={13}/>:null}{en.temperature||"Warm"}</span>{en.priority==="Urgent"&&<span className="urgentTag"><AlertTriangle size={13}/>Urgent attention</span>}</div></div><div className="crmButtons">{en.phone&&validPhone(en.phone)&&<a className="ghost small" target="_blank" rel="noreferrer" href={`https://wa.me/${wa(en.phone)}?text=${encodeURIComponent(message(en))}`} onClick={()=>patch(en,{status:"Contacted",lastContactChannel:"WhatsApp",lastContactAt:new Date().toISOString()})}><MessageCircle size={15}/>WhatsApp</a>}{en.email&&validEmail(en.email)&&<a className="ghost small" href={`mailto:${encodeURIComponent(en.email)}?subject=${encodeURIComponent("Your Coworx Central enquiry")}&body=${encodeURIComponent(message(en))}`} onClick={()=>patch(en,{status:"Contacted",lastContactChannel:"Email",lastContactAt:new Date().toISOString()})}><Mail size={15}/>Email</a>}<select aria-label={`Lead type for ${en.name}`} value={en.temperature||"Warm"} onChange={e=>patch(en,{temperature:e.target.value})}><option>Cold</option><option>Warm</option><option>Hot</option></select><select aria-label={`Priority for ${en.name}`} value={en.priority||"Normal"} onChange={e=>patch(en,{priority:e.target.value})}><option>Normal</option><option>Urgent</option></select><select aria-label={`Status for ${en.name}`} value={en.status||"New"} onChange={e=>patch(en,{status:e.target.value})}><option>New</option><option>Contacted</option><option>Follow-up</option><option>Converted</option><option>Closed</option></select></div></article>)}{!filtered.length&&<p className="muted">No enquiries match this view.</p>}</div>
  </section>;
}
