import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, Building2, Mic2, Monitor, Users, Upload, X } from "lucide-react";
import Dialog from "./Dialog";
import { DEFAULT_HOME_CONTENT, HomeContent, prepareContentImage, saveHomeContent, watchHomeContent } from "../lib/homeContent";

const icon=(id:string)=>id==="desk"?Monitor:id==="meeting"?Users:id==="conference"?Building2:Mic2;

export function HomepagePossibilities({fallbackImages={}}:any){
  const [content,setContent]=useState<HomeContent>(DEFAULT_HOME_CONTENT),[selected,setSelected]=useState<any>(null);
  useEffect(()=>watchHomeContent(setContent,()=>{}),[]);
  return <section className="homeSpaces" id="spaces"><div className="sectionHeading"><div><span className="eyebrow">{content.eyebrow}</span><h2>{content.title}</h2></div><p>{content.description}</p></div><div className="workspaceCards informationalCards">{content.cards.map((card,i)=>{const Icon=icon(card.id);const photos=card.photos?.length?card.photos:[fallbackImages[card.id]].filter(Boolean);return <article key={card.id}><button className="workspaceImage" onClick={()=>setSelected({...card,photos})} aria-label={`Learn more about ${card.description}`}><img src={photos[0]} alt={card.description} loading="lazy"/><span className="spaceNumber">0{i+1}</span><span className="spaceArrow"><ArrowUpRight size={19}/></span></button><div className="workspaceCardCopy"><span className="spaceType"><Icon size={15}/>{card.description}</span><h3>{card.title}</h3><button className="spacePrice" onClick={()=>setSelected({...card,photos})}>View details <ArrowRight size={17}/></button></div></article>})}</div>{selected&&<Dialog title={selected.title} wide onClose={()=>setSelected(null)}><p className="homeDetailLead">{selected.description}</p><p>{selected.body}</p>{selected.photos?.length>0&&<div className="homeDetailGallery">{selected.photos.map((src:string,i:number)=><img src={src} alt={`${selected.title} ${i+1}`} key={i}/>)}</div>}</Dialog>}</section>;
}

export function HomepageContentEditor({onFlash}:any){
  const [content,setContent]=useState<HomeContent>(DEFAULT_HOME_CONTENT),[busy,setBusy]=useState(false);
  useEffect(()=>watchHomeContent(setContent,e=>onFlash(e.message)),[]);
  const patchCard=(id:string,data:any)=>setContent({...content,cards:content.cards.map(c=>c.id===id?{...c,...data}:c)});
  const upload=async(id:string,files:FileList|null)=>{if(!files?.length)return;setBusy(true);try{const card=content.cards.find(c=>c.id===id)!;const capacity=Math.max(0,4-(card.photos?.length||0));if(!capacity)throw Error("A card can contain up to 4 photos.");const photos=[];for(const file of Array.from(files).slice(0,capacity))photos.push(await prepareContentImage(file));patchCard(id,{photos:[...(card.photos||[]),...photos]});onFlash("Photos prepared. Save homepage content to publish them.");}catch(e:any){onFlash(e.message);}finally{setBusy(false);}};
  return <section className="opsPanel homepageEditor"><div className="panelHead"><div><span className="eyebrow">HOMEPAGE CONTENT</span><h3>“One place” information cards</h3><small>Edit the heading and detailed information customers see when they open each card.</small></div></div><div className="fieldGrid"><label>Eyebrow<input value={content.eyebrow} onChange={e=>setContent({...content,eyebrow:e.target.value})}/></label><label>Section title<input value={content.title} onChange={e=>setContent({...content,title:e.target.value})}/></label></div><label>Section description<textarea value={content.description} onChange={e=>setContent({...content,description:e.target.value})}/></label><div className="homepageEditorCards">{content.cards.map(card=><article className="surface" key={card.id}><b>{card.id.toUpperCase()}</b><label>Card title<input value={card.title} onChange={e=>patchCard(card.id,{title:e.target.value})}/></label><label>Short description<input value={card.description} onChange={e=>patchCard(card.id,{description:e.target.value})}/></label><label>Detailed body<textarea value={card.body} onChange={e=>patchCard(card.id,{body:e.target.value})}/></label><label className="uploadButton"><Upload size={16}/>Add photos (up to 4)<input type="file" accept="image/*" multiple disabled={busy} onChange={e=>upload(card.id,e.target.files)}/></label>{card.photos?.length>0&&<div className="editorPhotoStrip">{card.photos.map((src,i)=><span key={i}><img src={src} alt=""/><button type="button" aria-label="Remove photo" onClick={()=>patchCard(card.id,{photos:card.photos.filter((_,n)=>n!==i)})}><X size={14}/></button></span>)}</div>}</article>)}</div><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await saveHomeContent(content);onFlash("Homepage information cards published.");}catch(e:any){onFlash(e.message);}finally{setBusy(false);}}}>{busy?"Saving…":"Publish homepage content"}</button></section>;
}
