import { addDays, localToday } from "../pages/types";
import { officeHours, sessionHours } from "../lib/business";
export default function HoursEditor({value:p,onChange,bookings=[]}:any) {
  const patch=(x:any)=>onChange({...p,...x});
  const future=bookings.filter((b:any)=>b.status==="Confirmed"&&(b.endDate||b.date)>=localToday());
  const affected=future.filter((b:any)=>(b.dates||[b.date]).some((date:string)=>{if(date<localToday())return false;const h=officeHours(date,p),old=sessionHours(b,date);return h.closed||old.start<h.start||old.end>h.end;}));
  return <div className="hoursEditor"><div className="fieldGrid"><label>Default opening time<input type="time" value={p.businessStart} onChange={e=>patch({businessStart:e.target.value})}/></label><label>Default closing time<input type="time" value={p.businessEnd} onChange={e=>patch({businessEnd:e.target.value})}/></label></div><p>Sundays are always holidays. Desk sessions end at the scheduled closing time. All times are India time.</p>
    <details><summary>Weekday hours</summary>{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((label,i)=>{const key=i+1,h=p.weekly?.[key]||{start:p.businessStart,end:p.businessEnd,closed:false};return <div className="scheduleRow" key={key}><b>{label}</b><input aria-label={`${label} opens`} type="time" disabled={h.closed} value={h.start} onChange={e=>patch({weekly:{...p.weekly,[key]:{...h,start:e.target.value}}})}/><input aria-label={`${label} closes`} type="time" disabled={h.closed} value={h.end} onChange={e=>patch({weekly:{...p.weekly,[key]:{...h,end:e.target.value}}})}/><label className="checkLabel"><input type="checkbox" checked={!!h.closed} onChange={e=>patch({weekly:{...p.weekly,[key]:{...h,closed:e.target.checked}}})}/>Closed</label><button className="textButton" onClick={()=>{const weekly={...p.weekly};delete weekly[key];patch({weekly});}}>Use default</button></div>;})}</details>
    <h3>Seasonal schedules</h3><p>Set an effective date range for winter, summer or another season.</p>{(p.seasons||[]).map((s:any,i:number)=><div className="scheduleCard" key={i}><div className="fieldGrid">{[["name","Name","text"],["from","From","date"],["to","Until","date"],["start","Opens","time"],["end","Closes","time"]].map(([key,label,type])=><label key={key}>{label}<input type={type} value={s[key]||""} onChange={e=>patch({seasons:p.seasons.map((r:any,n:number)=>n===i?{...r,[key]:e.target.value}:r)})}/></label>)}</div><button className="textButton dangerText" onClick={()=>patch({seasons:p.seasons.filter((_:any,n:number)=>n!==i)})}>Remove season</button></div>)}<button className="ghost" onClick={()=>patch({seasons:[...(p.seasons||[]),{name:"",from:localToday(),to:addDays(localToday(),90),start:p.businessStart,end:p.businessEnd}]})}>Add seasonal hours</button>
    <h3>One-day exceptions</h3>{(p.exceptions||[]).map((s:any,i:number)=><div className="scheduleCard" key={i}><div className="fieldGrid">{[["date","Date","date"],["reason","Reason","text"],["start","Opens","time"],["end","Closes","time"]].map(([key,label,type])=><label key={key}>{label}<input type={type} disabled={s.closed&&type==="time"} value={s[key]||""} onChange={e=>patch({exceptions:p.exceptions.map((r:any,n:number)=>n===i?{...r,[key]:e.target.value}:r)})}/></label>)}<label className="checkLabel"><input type="checkbox" checked={!!s.closed} onChange={e=>patch({exceptions:p.exceptions.map((r:any,n:number)=>n===i?{...r,closed:e.target.checked}:r)})}/>Closed all day</label></div><button className="textButton dangerText" onClick={()=>patch({exceptions:p.exceptions.filter((_:any,n:number)=>n!==i)})}>Remove exception</button></div>)}<button className="ghost" onClick={()=>patch({exceptions:[...(p.exceptions||[]),{date:localToday(),reason:"",start:p.businessStart,end:p.businessEnd,closed:false}]})}>Add date exception</button>
    <div className="noticeBox"><b>Existing confirmed bookings retain their agreed session times.</b>{affected.length>0?<><p>{affected.length} existing bookings conflict with these hours. Review them before applying the new schedule.</p>{affected.slice(0,10).map((b:any)=><p key={b.id}>{b.customerName||b.customerEmail} · {b.label} · {b.date}–{b.endDate||b.date}</p>)}</>:<p>No existing booking conflicts found.</p>}</div>
    <h3>Next seven days</h3><div className="dateChips">{Array.from({length:7},(_,i)=>addDays(localToday(),i)).map(date=>{const h=officeHours(date,p);return <span key={date}><b>{date}</b> {h.closed?h.reason:`${h.start}–${h.end}`}</span>;})}</div>
  </div>;
}
