import {useEffect,useMemo,useState} from "react";
import {LogIn,LogOut,Menu,ShieldCheck,X} from "lucide-react";
import {GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut} from "firebase/auth";
import {doc,updateDoc} from "firebase/firestore";
import {auth,db,isFirebaseConfigured} from "./firebase";
import {DEFAULT_PRICING,Role,Space,Booking,today,addHours,withinBusinessHours,BUSINESS_START,BUSINESS_END} from "./pages/types";
import {ensureUser,backfillUserBookings,loadPricing,savePricing,assignManager,acceptManager,createOffer,confirmBooking,revokeBooking,cancelBooking,createBooking,watchUser,watchAllBookings,watchPendingBookings,watchBookingLocks,watchOffers,watchRoleAssignment,watchUsers,saveUserProfile,loadDeskPricing,saveDeskPricing,loadWifi,saveWifi,loadUpi,saveUpi,getUserByEmail,markCheckIn,markCheckOut} from "./lib/firestore";
import Home from "./pages/Home";import BookingPage from "./pages/Booking";import Amenities from "./pages/Amenities";import {Account,OffersPage,ManagerPage,AdminPage,LoginPage} from "./pages/Other";
import {COWORX_LOGO} from "./assets/logoData";
import "./styles.css";import "./mobile.css";import "./branding.css";
const active=(l:any)=>l.status==="Confirmed"||(l.status==="Pending"&&(l.expiresAt?.toMillis?.()||0)>Date.now());
const maxHours=(locks:any[],space:Space,start:string)=>{let n=0;for(let i=0;i<10;i++){const slot=addHours(start,i);if(slot>=BUSINESS_END||locks.some(l=>l.inventoryId===space&&active(l)&&l.start===slot))break;n++;}return n;};
const Logo=()=> <img className="coworxLogoImage" src={COWORX_LOGO} alt="coworx central" />;
export default function App(){
 const [user,setUser]=useState<any>(null),[role,setRole]=useState<Role>("User"),[page,setPage]=useState("home"),[menuOpen,setMenuOpen]=useState(false),[isMobile,setIsMobile]=useState(()=>typeof window!=="undefined"&&window.innerWidth<=900),[theme,setTheme]=useState<"dark"|"light">((localStorage.getItem("coworx-theme") as any)||"dark");
 const [date,setDate]=useState(today()),[space,setSpace]=useState<Space>("desk"),[selectedSeats,setSelectedSeats]=useState<string[]>([]),[conf,setConf]=useState("09:00"),[meeting,setMeeting]=useState("09:00"),[pod,setPod]=useState("09:00"),[meetingDuration,setMeetingDuration]=useState(1),[confDuration,setConfDuration]=useState(1),[podDuration,setPodDuration]=useState(1),[prices,setPrices]=useState<any>(DEFAULT_PRICING),[deskPrices,setDeskPrices]=useState<any>({});
 const [bookings,setBookings]=useState<Booking[]>([]),[staffBookings,setStaffBookings]=useState<Booking[]>([]),[pendingBookings,setPendingBookings]=useState<Booking[]>([]),[locks,setLocks]=useState<any[]>([]),[offers,setOffers]=useState<any[]>([]),[assignment,setAssignment]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[flash,setFlash]=useState(""),[loginError,setLoginError]=useState("");
 const [managerEmail,setManagerEmail]=useState(""),[customerEmail,setCustomerEmail]=useState(""),[phoneNumber,setPhoneNumber]=useState(()=>localStorage.getItem("coworx-phone")||""),[staffBooking,setStaffBooking]=useState(false);
 const [wifi,setWifi]=useState<any>({ssid:"",password:"",note:""}),[upi,setUpi]=useState<any>({upiId:"",merchantName:"Coworx Central"});
 const [offerForm,setOfferForm]=useState({title:"",description:"",type:"percent" as any,value:10,targetType:"all" as any,targetEmail:""});
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("coworx-theme",theme)},[theme]);
 useEffect(()=>{const mq=window.matchMedia("(max-width:900px)"),sync=()=>setIsMobile(mq.matches);sync();mq.addEventListener?.("change",sync);return()=>mq.removeEventListener?.("change",sync)},[]);
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(!u){setRole("User");return}try{const r=await ensureUser(u);setRole(r);await backfillUserBookings(u.uid)}catch(e:any){setFlash(e?.message||"Could not load account")}}),[]);
 useEffect(()=>{loadPricing().then(setPrices).catch(()=>{});loadWifi().then(setWifi).catch(()=>{});loadUpi().then(setUpi).catch(()=>{})},[]);
 useEffect(()=>{if(!user){setBookings([]);setOffers([]);setAssignment(null);setLocks([]);return}const a=watchUser(user.uid,user.email||"",setBookings,e=>setFlash(e?.message||"Could not load bookings")),b=watchOffers(user.email||"",setOffers),c=watchRoleAssignment(user.email||"",setAssignment),d=watchBookingLocks(date,setLocks,e=>setFlash(e?.message||"Could not load availability"));loadDeskPricing(date,{}).then(setDeskPrices).catch(()=>{});return()=>{a();b();c();d()}},[user,date]);
 useEffect(()=>{if(!user||role==="User"){setPendingBookings([]);setStaffBookings([]);setUsers([]);return}const a=watchPendingBookings(setPendingBookings,e=>setFlash(e?.message||"Could not load pending requests")),b=watchAllBookings(setStaffBookings,e=>setFlash(e?.message||"Could not load bookings")),c=watchUsers(setUsers,e=>setFlash(e?.message||"Could not load users"));return()=>{a();b();c()}},[user,role]);
 const activeLocks=useMemo(()=>locks.filter(l=>l.date===date&&active(l)),[locks,date]);
 const booked=useMemo(()=>activeLocks.map(l=>l.inventoryId),[activeLocks]);
 const deskData=useMemo(()=>selectedSeats.map(id=>{const premium=[2,3,9,15,22].includes(Number(id.replace("D","")));return{price:Number(deskPrices[id]??(premium?prices.desk_premium:prices.desk_basic))}}),[selectedSeats,deskPrices,prices]);
 const isDesk=space==="desk"||space==="cubicle",start=isDesk?undefined:space==="conference"?conf:space==="meeting"?meeting:pod;
 const maximum=!isDesk&&start?maxHours(activeLocks,space,start):0,duration=isDesk?1:space==="conference"?confDuration:space==="meeting"?meetingDuration:podDuration,end=start?addHours(start,duration):undefined;
 const base=isDesk?deskData.reduce((n,s)=>n+s.price,0):space==="conference"?prices.conference_hourly*duration:space==="meeting"?prices.meeting_hourly*duration:prices.podcast_hourly*duration;
 const off=offers[0],offerDiscount=off?(off.type==="percent"?Math.round(base*off.value/100):Math.min(base,Number(off.value)||0)):0,bulkDiscount=isDesk&&selectedSeats.length>5?Math.round(base*.1):0,discount=Math.min(base,offerDiscount+bulkDiscount),total=Math.max(0,base-discount);
 useEffect(()=>{if(isDesk||!start||maximum<1)return;if(space==="conference"&&confDuration>maximum)setConfDuration(maximum);if(space==="meeting"&&meetingDuration>maximum)setMeetingDuration(maximum);if(space==="podcast"&&podDuration>maximum)setPodDuration(maximum)},[space,start,maximum,confDuration,meetingDuration,podDuration,isDesk]);
 const nav=(p:string)=>{if(p==="book"&&!user){setPage("login");setFlash("Google sign-in is required before booking.");return}setPage(p);setMenuOpen(false)};
 async function login(){if(!isFirebaseConfigured){setLoginError("Edit src/firebaseConfig.ts with your Firebase Web App values.");return}try{await signInWithPopup(auth,new GoogleAuthProvider());setPage("home");setLoginError("")}catch(e:any){setLoginError(e?.message||"Google login failed")}}
 async function book(profile?:any){if(!user){nav("book");return}if(staffBooking&&role==="User")return setFlash("Only Admin or Manager can book for a walk-in customer.");const targetEmail=staffBooking?customerEmail.trim().toLowerCase():user.email,phone=(profile?.mobile||phoneNumber).trim();if(!targetEmail||!targetEmail.includes("@"))return setFlash("Enter the customer's email address.");if(!/^\+?[0-9\s()-]{10,18}$/.test(phone))return setFlash("Enter a valid mobile number.");localStorage.setItem("coworx-phone",phone);if(profile&&!staffBooking){try{await saveUserProfile(user.uid,{phone,gender:profile.gender,dob:profile.dob,profession:profile.profession})}catch{}}
 if(isDesk&&!selectedSeats.length)return setFlash("Select at least one desk first.");if(start&&end&&!withinBusinessHours(start,end))return setFlash(`Bookings are only allowed from ${BUSINESS_START} to ${BUSINESS_END}.`);if(!isDesk&&(!maximum||duration>maximum))return setFlash("That duration is unavailable. Choose another start time or shorter duration.");
 try{const ids=isDesk?selectedSeats.map(s=>`desk-${s}`):[space],lockKeys=isDesk?selectedSeats.map(s=>`${date}_desk-${s}_day`):Array.from({length:duration},(_,i)=>`${date}_${space}_${addHours(start||BUSINESS_START,i)}`);let customerName=user.displayName||user.email?.split("@")[0]||"Coworx Member";if(staffBooking){const existing=await getUserByEmail(targetEmail);if(existing?.name)customerName=existing.name}await createBooking({date,space,inventoryId:ids[0],inventoryIds:ids,lockKeys,label:isDesk?`${selectedSeats.length} Desk${selectedSeats.length===1?"":"s"}`:space==="meeting"?"Meeting Room":space==="conference"?"Conference Room":"Creator Studio",userId:staffBooking?`walkin:${targetEmail}`:user.uid,userEmail:user.email||"",customerName,customerEmail:targetEmail,customerPhone:phone,createdByRole:staffBooking?role:"User",walkIn:staffBooking,start,end,durationHours:duration,base,discount,total,offerId:off?.id||null,status:staffBooking?"Confirmed":"Pending"});if(!staffBooking)window.open(`https://wa.me/919970836509?text=${encodeURIComponent(`Hello Coworx Central, I want to book ${isDesk?`${selectedSeats.length} desk(s): ${selectedSeats.join(", ")}`:space==="meeting"?`Meeting Room ${start}-${end}`:space==="conference"?`Conference Room ${start}-${end}`:`Creator Studio ${start}-${end}`} on ${date}. Total: ₹${total}. Contact: ${phone}.`)}`,"_blank");setFlash(staffBooking?`Booking confirmed for ${targetEmail}.`:`Request created for ${targetEmail}. Slot held for 15 minutes.`);setPage("bookings");setSelectedSeats([]);setStaffBooking(false);setCustomerEmail("")}catch(e:any){setFlash(e?.message||"Booking failed")}}
 async function doAssign(){try{await assignManager(managerEmail,user.uid);setManagerEmail("");setFlash("Manager invitation sent.")}catch(e:any){setFlash(e?.message||"Unable to assign manager")}}
 async function doOffer(){try{await createOffer(offerForm,user.uid);setOfferForm({title:"",description:"",type:"percent",value:10,targetType:"all",targetEmail:""});setFlash("Offer created.")}catch(e:any){setFlash(e?.message||"Offer creation failed")}}
 async function doConfirm(id:string,staffDiscount=0,paymentReceived?:number,paymentMethod?:string,paymentRef?:string){try{await confirmBooking(id,user.uid,staffDiscount,paymentReceived,paymentMethod,paymentRef);setFlash("Booking confirmed and payment recorded.")}catch(e:any){setFlash(e?.message||"Could not confirm booking")}}
 async function doRevoke(id:string){try{await revokeBooking(id,user.uid);setFlash("Booking request revoked and slot released.")}catch(e:any){setFlash(e?.message||"Could not revoke request")}}
 async function doCancel(id:string){try{await cancelBooking(id,user.uid);setFlash("Booking cancelled and availability released.")}catch(e:any){setFlash(e?.message||"Could not cancel booking")}}
 async function accept(){try{await acceptManager(assignment,user.uid);setRole("Manager");setAssignment({...assignment,status:"accepted"});setFlash("Manager role activated.")}catch(e:any){setFlash(e?.message||"Could not activate role")}}
 const resetBook=()=>{setSpace("desk");setSelectedSeats([]);setStaffBooking(false);nav("book")};
 const mobile=isMobile?<div className={`mobileMenu ${menuOpen?"open":""}`}><div className="mobileMenuHead"><Logo/><button onClick={()=>setMenuOpen(false)} aria-label="Close menu"><X size={19}/></button></div><button onClick={resetBook}>Book</button>{user&&<button onClick={()=>nav("bookings")}>My Bookings</button>}{user&&<button onClick={()=>nav("offers")}>Offers</button>}<button onClick={()=>nav("amenities")}>Amenities</button>{role!=="User"&&user&&<button onClick={()=>nav("manager")}>Manager{pendingBookings.length?` · ${pendingBookings.length}`:""}</button>}{role==="Admin"&&user&&<button onClick={()=>nav("admin")}>Admin</button>}</div>:null;
 return <div className="app"><header><button className="brand" onClick={()=>nav("home")}><Logo/></button><nav className="desktopNav"><button onClick={resetBook}>Book</button>{user&&<><button onClick={()=>nav("bookings")}>My Bookings</button><button onClick={()=>nav("offers")}>Offers</button></>}<button onClick={()=>nav("amenities")}>Amenities</button>{role!=="User"&&user&&<button className="staffNav" onClick={()=>nav("manager")}>Manager{pendingBookings.length?` · ${pendingBookings.length}`:""}</button>}{role==="Admin"&&user&&<button className="staffNav" onClick={()=>nav("admin")}>Admin</button>}</nav><div className="headActions">{user?<><span className="emailChip">{user.email}</span><button className="logout" onClick={()=>signOut(auth)}><LogOut size={16}/></button></>:<button className="loginChip" onClick={login}><LogIn size={16}/> Google</button>}<button className="theme" onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?"☀":"☾"}</button>{isMobile&&<button className="menuBtn" aria-label="Open menu" onClick={()=>setMenuOpen(!menuOpen)}><Menu size={21}/></button>}</div></header>{mobile}{assignment?.status==="pending"&&<div className="roleBanner"><div><ShieldCheck/><span><b>Manager invitation</b><small>Admin has invited {user.email}.</small></span></div><div><button className="primary small" onClick={accept}>Accept</button><button className="ghost small" onClick={()=>updateDoc(doc(db,"roleAssignments",assignment.id),{status:"declined"})}>Decline</button></div></div>}{!isFirebaseConfigured&&<div className="configBanner">Edit <code>src/firebaseConfig.ts</code> with your Firebase Web App values.</div>}{flash&&<div className="toast">{flash}<button onClick={()=>setFlash("")}><X size={15}/></button></div>}
 {page==="home"&&<Home book={s=>{setSpace(s);setSelectedSeats([]);setStaffBooking(false);nav("book")}} prices={prices}/>} {page==="login"&&<LoginPage onLogin={login} error={loginError}/>} {page==="book"&&user&&<BookingPage date={date} setDate={setDate} space={space} setSpace={setSpace} selectedSeats={selectedSeats} setSelectedSeats={setSelectedSeats} booked={booked} roomLocks={activeLocks} prices={prices} deskPrices={deskPrices} conf={conf} setConf={setConf} confDuration={confDuration} setConfDuration={setConfDuration} meeting={meeting} setMeeting={setMeeting} meetingDuration={meetingDuration} setMeetingDuration={setMeetingDuration} pod={pod} setPod={setPod} podDuration={podDuration} setPodDuration={setPodDuration} base={base} total={total} discount={discount} bulkDiscount={bulkDiscount} offerDiscount={offerDiscount} offers={offers} book={book} staff={role!=="User"} staffBooking={staffBooking} setStaffBooking={setStaffBooking} customerEmail={customerEmail} setCustomerEmail={setCustomerEmail} phoneNumber={phoneNumber} setPhoneNumber={setPhoneNumber} user={user}/>} {page==="bookings"&&user&&<Account bookings={role==="User"?bookings:staffBookings} staff={role!=="User"} onCancel={doCancel} onCheckIn={markCheckIn} onCheckOut={markCheckOut} wifi={wifi}/>} {page==="offers"&&user&&<OffersPage offers={offers}/>} {page==="amenities"&&<Amenities/>} {page==="manager"&&role!=="User"&&user&&<ManagerPage bookings={pendingBookings} form={offerForm} setForm={setOfferForm} createOffer={doOffer} confirm={doConfirm} revoke={doRevoke}/>} {page==="admin"&&role==="Admin"&&user&&<AdminPage prices={prices} setPrices={setPrices} save={()=>savePricing(prices).then(()=>setFlash("Pricing saved."))} date={date} setDate={setDate} deskPrices={deskPrices} setDeskPrices={setDeskPrices} saveDeskPrices={()=>saveDeskPricing(date,deskPrices).then(()=>setFlash(`Desk pricing saved for ${date}.`))} copyPrice={(v:number)=>setDeskPrices(Object.fromEntries(Array.from({length:22},(_,i)=>{const id=`D${String(i+1).padStart(2,"0")}`;return[id,v]})))} wifi={wifi} setWifi={setWifi} saveWifi={()=>saveWifi(wifi).then(()=>setFlash("Wi-Fi credentials saved."))} upi={upi} setUpi={setUpi} saveUpi={()=>saveUpi(upi).then(()=>setFlash("UPI settings saved."))} email={managerEmail} setEmail={setManagerEmail} assign={doAssign} form={offerForm} setForm={setOfferForm} createOffer={doOffer} bookings={pendingBookings} allBookings={staffBookings} users={users} revoke={doRevoke} confirm={doConfirm}/>}<footer><b>coworx central</b><span>Solapur City</span><a href="https://share.google/jMdqj9zrUAniaTc5b" target="_blank" rel="noreferrer">Google Maps</a></footer></div>;
}
